fn shell_backblaze_client() -> &'static str {
    r####"    let backblazePollTimer = null;
    function scheduleBackblazeStatusPoll(running) { if (backblazePollTimer) window.clearTimeout(backblazePollTimer); backblazePollTimer = running ? window.setTimeout(() => { void hydrateBackblaze(); }, 5000) : null; }
    function backblazeText(value) { return value === null || value === undefined || value === '' ? '—' : String(value); }
    function backblazeTime(value) { return value === null || value === undefined ? 'Never' : new Date(Number(value) * 1000).toLocaleString(); }
    function backblazeBytes(value) { if (!Number.isFinite(Number(value))) return 'Unknown'; const units=['B','KB','MB','GB','TB']; let size=Number(value), unit=0; while (size >= 1024 && unit < units.length - 1) { size /= 1024; unit += 1; } return `${size >= 10 || unit === 0 ? size.toFixed(0) : size.toFixed(1)} ${units[unit]}`; }
    function backblazeBadge(node, ok) { if (!node) return; node.className=`ui-badge ${ok ? 'ui-badge--success' : 'ui-badge--danger'}`; node.textContent=ok ? 'Ready' : 'Needs attention'; }
    function backblazePathRow(value, locked=false) { const row=document.createElement('div'); row.className='backblaze-path-input'; const input=document.createElement('input'); input.type='text'; input.name='paths'; input.required=true; input.value=value || ''; input.autocomplete='off'; input.disabled=locked; input.readOnly=locked; const remove=document.createElement('button'); remove.type='button'; remove.className='ui-button ui-button--secondary'; remove.textContent='Remove'; remove.disabled=locked; remove.hidden=locked; remove.addEventListener('click', () => row.remove()); row.append(input, remove); return row; }
    function renderBackblazeConfig(status) { const form=document.querySelector('[data-backblaze-config-form]'); const editor=document.querySelector('[data-backblaze-path-editor]'); if (!form || !editor) return; const config=status?.checks?.config || {}; const locked=config.ok === true; const keyId=form.elements.keyId, applicationKey=form.elements.applicationKey, bucket=form.elements.bucket, prefix=form.elements.prefix, save=document.querySelector('[data-backblaze-config-save]'), add=document.querySelector('[data-backblaze-path-add]'), lock=document.querySelector('[data-backblaze-config-lock]'), caption=document.querySelector('[data-backblaze-config-caption]'); if (locked) { bucket.value=config.bucket || ''; prefix.value=config.prefix || ''; editor.replaceChildren(...(Array.isArray(config.paths) ? config.paths : []).map(path => backblazePathRow(path, true))); } else if (!editor.children.length) editor.append(backblazePathRow('')); editor.querySelectorAll('input[name="paths"]').forEach(input => { input.disabled=locked; input.readOnly=locked; }); editor.querySelectorAll('button').forEach(button => { button.disabled=locked; button.hidden=locked; }); [keyId,applicationKey,bucket,prefix].forEach(input => { input.disabled=locked; input.readOnly=locked; }); if (save) save.hidden=locked; if (add) add.hidden=locked; if (lock) lock.hidden=!locked; if (caption) caption.textContent=locked ? 'Locked after initial configuration' : ''; }
    function renderBackblazeChecks(status) { const checks=status?.checks || {}; const config=checks.config || {}; backblazeBadge(document.querySelector('[data-backblaze-check="restic"]'), checks.restic?.ok === true); backblazeBadge(document.querySelector('[data-backblaze-check="config"]'), config.ok === true); backblazeBadge(document.querySelector('[data-backblaze-check="credentials"]'), checks.credentials?.ok === true); const configLabel=document.querySelector('[data-backblaze-config-label]'); if (configLabel) configLabel.textContent=config.ok === true ? `Bucket: ${backblazeText(config.bucket)}${config.prefix ? ` · Prefix: ${config.prefix}` : ''}` : backblazeText(config.reason); renderBackblazeConfig(status); }
    function renderBackblazePaths(status) { const target=document.querySelector('[data-backblaze-paths]'); if (!target) return; const paths=status?.checks?.config?.paths; target.replaceChildren(); if (!Array.isArray(paths) || paths.length === 0) { target.textContent=status?.checks?.config?.reason || 'Backblaze is not configured.'; return; } paths.forEach(path => { const row=document.createElement('div'); row.className='backblaze-path-row'; row.textContent=path; target.append(row); }); }
    function renderBackblazeSnapshots(payload) { const body=document.querySelector('[data-backblaze-snapshots]'); const empty=document.querySelector('[data-backblaze-snapshots-empty]'); if (!body || !empty) return; body.replaceChildren(); const snapshots=payload?.ok === true && Array.isArray(payload.snapshots) ? payload.snapshots : []; if (snapshots.length === 0) { empty.hidden=false; empty.textContent=payload?.ok === false ? backblazeText(payload.reason) : 'No snapshots yet'; return; } empty.hidden=true; snapshots.forEach(snapshot => { const row=document.createElement('tr'); const paths=Array.isArray(snapshot.paths) ? snapshot.paths.join(', ') : '—'; [['Time', backblazeText(snapshot.time)], ['ID', backblazeText(snapshot.short_id || snapshot.id)], ['Paths', paths || '—']].forEach(([label, value]) => { const cell=document.createElement('td'); cell.dataset.label=label; cell.textContent=value; row.append(cell); }); body.append(row); }); }
    function renderBackblazeStatus(status) { const badge=document.querySelector('[data-backblaze-badge]'); const button=document.querySelector('[data-backblaze-run]'); if (!badge) return; const configured=status?.configured === true; const running=status?.running === true; const state=running ? 'Running' : !configured ? 'Not configured' : status?.last_run_ok === true ? 'Success' : status?.last_run_ok === false ? 'Failed' : 'Never run'; const tone=running ? 'ui-badge--info' : !configured || status?.last_run_ok === false ? 'ui-badge--danger' : status?.last_run_ok === true ? 'ui-badge--success' : 'ui-badge--secondary'; badge.className=`ui-badge ${tone}`; badge.textContent=state; const stateRow=document.querySelector('[data-backblaze-state]'); const timeRow=document.querySelector('[data-backblaze-time]'); const sizeRow=document.querySelector('[data-backblaze-size]'); const resultRow=document.querySelector('[data-backblaze-status]'); if (stateRow) stateRow.textContent=state; if (timeRow) timeRow.textContent=backblazeTime(status?.last_run_at); if (sizeRow) sizeRow.textContent=backblazeBytes(status?.last_backup_size_bytes); if (resultRow) resultRow.textContent=!configured ? backblazeText(status?.reason || 'Backup is not configured') : status?.last_run_ok === false ? 'The last backup did not complete.' : status?.last_run_ok === true ? 'The last backup completed.' : 'No completed backup is recorded.'; if (button) button.disabled=!configured || running; renderBackblazeChecks(status); scheduleBackblazeStatusPoll(running); }
    async function hydrateBackblaze() { if (!viewportFamilyAdmitted('backblaze')) return; try { const [statusResponse,snapshotsResponse]=await Promise.all([fetch('/api/backblaze/status',{cache:'no-store'}),fetch('/api/backblaze/snapshots',{cache:'no-store'})]); renderBackblazeStatus(await statusResponse.json()); renderBackblazeSnapshots(await snapshotsResponse.json()); } catch (_) { renderBackblazeStatus({configured:false,reason:'Backup status is unavailable'}); renderBackblazeSnapshots({ok:false,reason:'Backup snapshots are unavailable'}); } }
    async function runBackblaze() { const result=document.querySelector('[data-backblaze-result]'); const button=document.querySelector('[data-backblaze-run]'); if (button) button.disabled=true; if (result) result.textContent='Starting backup…'; try { const response=await fetch('/api/backblaze/run',{method:'POST',cache:'no-store'}); const payload=await response.json().catch(() => ({})); if (result) result.textContent=payload.message || (response.ok ? 'Backup started.' : 'Backup could not start.'); await hydrateBackblaze(); } catch (_) { if (result) result.textContent='Backup could not start.'; await hydrateBackblaze(); } }
    async function saveBackblazeConfig(event) { event.preventDefault(); const form=event.currentTarget; const result=document.querySelector('[data-backblaze-config-result]'); const paths=[...form.querySelectorAll('input[name="paths"]')].map(input => input.value.trim()).filter(Boolean); const payload={keyId:form.elements.keyId.value,applicationKey:form.elements.applicationKey.value,bucket:form.elements.bucket.value,prefix:form.elements.prefix.value,paths}; if (result) result.textContent='Saving configuration…'; try { const response=await fetch('/api/backblaze/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'}); const body=await response.json().catch(() => ({})); if (!response.ok || body.ok === false) { if (result) result.textContent=`${body.step || 'config'}: ${body.reason || ''}`; return; } form.elements.applicationKey.value=''; if (result) result.textContent='Configuration saved and locked'; await hydrateBackblaze(); } catch (error) { if (result) result.textContent=error instanceof Error ? error.message : String(error); } }
    document.body.addEventListener('click', event => { if (event.target.closest('[data-backblaze-path-add]')) { const editor=document.querySelector('[data-backblaze-path-editor]'); if (editor) editor.append(backblazePathRow('')); } }, true);
    document.body.addEventListener('submit', event => { const form=event.target.closest('[data-backblaze-config-form]'); if (form) void saveBackblazeConfig(event); }, true);
    document.body.addEventListener('click', event => { const run=event.target.closest('[data-backblaze-run]'); if (run) { event.preventDefault(); void runBackblaze(); } }, true);
"####
}
