fn shell_backblaze_client() -> &'static str {
    r####"""
    let backblazeState = { bucket: null, data: null };
    function backblazeEsc(v) { return String(v || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
    function renderBackblazeBuckets(data) { const host=document.querySelector('[data-backblaze-buckets]'); if (!host) return; host.replaceChildren(); const buckets=Array.isArray(data && data.buckets)?data.buckets:[]; if (!buckets.length) { host.textContent='No buckets configured.'; return; } buckets.forEach(b => { const row=document.createElement('div'); row.className='backblaze-bucket-row'; row.dataset.bucket=b.bucket; const select=document.createElement('button'); select.type='button'; select.className='backblaze-bucket-select'; select.textContent=b.bucket; select.onclick=()=>selectBackblazeBucket(b.bucket); const remove=document.createElement('button'); remove.type='button'; remove.className='ui-button ui-button--secondary'; remove.textContent='Remove'; remove.onclick=()=>removeBackblazeBucket(b.bucket); const badge=document.createElement('span'); badge.className='ui-badge'; badge.textContent=b.status && b.status.running?'Running':(b.status && b.status.last_run_ok===true?'Ready':'Idle'); row.append(select,badge,remove); host.append(row); }); }
    async function hydrateBackblaze() { try { const r=await fetch('/api/backblaze/buckets',{cache:'no-store'}); backblazeState.data=await r.json(); renderBackblazeBuckets(backblazeState.data); if (!backblazeState.bucket && backblazeState.data.buckets && backblazeState.data.buckets.length) selectBackblazeBucket(backblazeState.data.buckets[0].bucket); else if (backblazeState.bucket) renderBackblazeItems(backblazeState.bucket); } catch (_) {} }
    function renderBackblazeItems(bucket) { const b=backblazeState.data && backblazeState.data.buckets && backblazeState.data.buckets.find(x=>x.bucket===bucket); const title=document.querySelector('[data-backblaze-selected]'), status=document.querySelector('[data-backblaze-bucket-status]'), items=document.querySelector('[data-backblaze-items]'), enc=document.querySelector('[data-backblaze-encrypted]'), run=document.querySelector('[data-backblaze-run]'), add=document.querySelector('[data-backblaze-item-add]'); if(!b||!items)return; title.textContent=b.bucket; status.textContent=(b.prefix||'(root)')+' · '+(b.status&&b.status.running?'Running':'Available'); enc.checked=b.encrypted===true; enc.disabled=false; run.disabled=b.status&&b.status.running===true; add.disabled=false; items.replaceChildren(); (b.items||[]).forEach(i=>{const row=document.createElement('div');row.className='backblaze-item-row';const label=document.createElement('span');label.textContent=i.path;const rm=document.createElement('button');rm.type='button';rm.className='ui-button ui-button--secondary';rm.textContent='Remove';rm.onclick=()=>fetch('/api/backblaze/buckets/'+encodeURIComponent(bucket)+'/items',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:i.path})}).then(hydrateBackblaze);row.append(label,rm);items.append(row);}); }
    function selectBackblazeBucket(bucket) { backblazeState.bucket=bucket; renderBackblazeItems(bucket); }
    async function addBackblazeBucket() { const bucket=prompt('B2 bucket name'); if(!bucket)return; const prefix=prompt('Prefix (optional)','')||''; const r=await fetch('/api/backblaze/buckets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bucket:bucket,prefix:prefix,encrypted:true,items:[]}),cache:'no-store'}); const body=await r.json().catch(()=>({})); document.querySelector('[data-backblaze-result]').textContent=body.ok===false?(body.reason||'Bucket could not be added'):'Bucket added and verified'; await hydrateBackblaze(); }
    async function removeBackblazeBucket(bucket) { if(!confirm('Remove '+bucket+'?'))return; await fetch('/api/backblaze/buckets/'+encodeURIComponent(bucket),{method:'DELETE'}); if(backblazeState.bucket===bucket)backblazeState.bucket=null; await hydrateBackblaze(); }
    document.body.addEventListener('click',e=>{if(e.target.closest('[data-backblaze-add]'))void addBackblazeBucket();if(e.target.closest('[data-backblaze-item-add]')){const p=prompt('Absolute path to back up');if(p)fetch('/api/backblaze/buckets/'+encodeURIComponent(backblazeState.bucket)+'/items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:p})}).then(hydrateBackblaze);}if(e.target.closest('[data-backblaze-run]'))fetch('/api/backblaze/buckets/'+encodeURIComponent(backblazeState.bucket)+'/run',{method:'POST'}).then(hydrateBackblaze);});
    document.body.addEventListener('change',e=>{if(e.target.matches('[data-backblaze-encrypted]'))fetch('/api/backblaze/buckets/'+encodeURIComponent(backblazeState.bucket)+'/toggle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({encrypted:e.target.checked})}).then(hydrateBackblaze);});
    hydrateBackblaze();
"""####
}
