fn shell_backblaze_client() -> &'static str {
    r####"""
    const state = { bucket: null, data: null, ledger: [], managerDrafts: {} };
    let statusPollTimer = null;
    let managerDraftBucket = null;
    let managerDraftBeforeOpen = null;
    const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const el = s => document.querySelector(s);
    const admitted = () => typeof viewportFamilyAdmitted === 'function' && viewportFamilyAdmitted('backblaze');
    const health = b => b?.status?.running ? 'RUNNING' : (b?.status?.last_run_ok === true ? 'GOOD' : (b?.status?.last_run_ok === false ? 'FAILED' : 'IDLE'));
    const forgejo = b => b?.managers?.forgejo || {};
    function setView(view) { document.querySelectorAll('[data-backblaze-view]').forEach(b => { const on=b.dataset.backblazeView===view; b.classList.toggle('is-active',on); b.setAttribute('aria-selected',on); }); document.querySelectorAll('[data-backblaze-panel]').forEach(p => p.hidden=p.dataset.backblazePanel!==view); if (view === 'ledger') void loadSnapshots(); }
    function renderLedger() { const host=el('[data-backblaze-ledger]'); if (host) host.innerHTML=state.ledger.length ? state.ledger.map(x=>`<div class="backblaze-ledger-row"><strong>${esc(x.bucket||'Backblaze')}</strong> ${esc(x.time||x.status||'Snapshot')} · ${esc(x.id||'—')}</div>`).join('') : '<p class="backblaze-empty">No restic snapshots available.</p>'; }
    function renderBuckets() { const host=el('[data-backblaze-buckets]'); if(!host)return; host.replaceChildren(); const buckets=Array.isArray(state.data?.buckets)?state.data.buckets:[]; if(!buckets.length){host.innerHTML='<p class="backblaze-empty">No buckets configured.</p>'; return;} buckets.forEach(b=>{const row=document.createElement('div');row.className='backblaze-bucket-row';row.dataset.bucket=b.bucket;const select=document.createElement('button');select.type='button';select.className='backblaze-bucket-select';select.setAttribute('aria-pressed',String(state.bucket===b.bucket));select.innerHTML=`<span>${esc(b.bucket)}</span><span class="ui-badge">${health(b)}</span>`;select.onclick=()=>selectBucket(b.bucket);const remove=document.createElement('button');remove.type='button';remove.className='backblaze-bucket-remove';remove.textContent='×';remove.title=`Remove ${b.bucket}`;remove.onclick=()=>removeBucket(b.bucket);row.append(select,remove);host.append(row);});}
    function renderManager(b) { const m=state.managerDrafts[b.bucket]||forgejo(b); const on=m.localNas===true||m.backblazeBackup===true; const indicator=el('[data-backblaze-manager-indicator]'); if(indicator)indicator.classList.toggle('is-lit',on); const open=el('[data-backblaze-manager-open]'); if(open)open.disabled=!b; }
    function renderSelected() { const b=state.data?.buckets?.find(x=>x.bucket===state.bucket); const title=el('[data-backblaze-selected]'); const save=el('[data-backblaze-save]'); const verify=el('[data-backblaze-verify]'); const update=el('[data-backblaze-update]'); const enc=el('[data-backblaze-encrypted]'); if(!b){if(title)title.textContent='Select a bucket';if(save)save.disabled=true;if(verify)verify.disabled=true;if(update)update.disabled=true;if(enc)enc.disabled=true;return;} title.textContent=b.bucket; el('[data-backblaze-bucket-status]').textContent=health(b); el('[data-backblaze-bucket-name]').value=b.bucket; const connected=el('[data-backblaze-connected]');connected.textContent=b.connected===true?'Connected':'Not connected';connected.classList.toggle('is-connected',b.connected===true);connected.classList.toggle('is-disconnected',b.connected!==true);enc.checked=b.encrypted===true;enc.disabled=false; const path=el('[data-backblaze-path]'), add=el('[data-backblaze-item-add]');path.disabled=false;add.disabled=false;if(save)save.disabled=false;if(verify)verify.disabled=false;if(update)update.disabled=false; const host=el('[data-backblaze-items]');host.replaceChildren();const items=Array.isArray(b.items)?b.items:[];if(!items.length)host.innerHTML='<p class="backblaze-empty">No files configured.</p>';items.forEach(i=>{const row=document.createElement('div');row.className='backblaze-path-row';row.innerHTML=`<span>${esc(i.path)}</span><button type="button" class="backblaze-path-remove" data-path="${esc(i.path)}">×</button>`;row.querySelector('button').onclick=()=>mutateItem(i.path,'DELETE');host.append(row);});renderManager(b);}
    function selectBucket(bucket){state.bucket=bucket;renderBuckets();renderSelected();const run=el('[data-backblaze-run]');if(run)run.disabled=!bucket;const selected=state.data?.buckets?.find(x=>x.bucket===bucket);if(selected&&selected.connected!==true&&selected.connected!==false)void verifyBucket(bucket);}
    async function getJson(url, init){const r=await fetch(url,{...init,cache:'no-store'});return r.json().catch(()=>({ok:false,reason:'Invalid response'}));}
    async function loadSnapshots(){if(!admitted())return;const snaps=await getJson('/api/backblaze/snapshots'+(state.bucket?'?bucket='+encodeURIComponent(state.bucket):''));state.ledger=Array.isArray(snaps?.snapshots)?snaps.snapshots:[];renderLedger();}
    function clearStatusPoll(){if(statusPollTimer!==null){window.clearTimeout(statusPollTimer);statusPollTimer=null;}}
    function scheduleStatusPoll(){clearStatusPoll();if(!state.data?.running||!admitted())return;statusPollTimer=window.setTimeout(()=>{statusPollTimer=null;if(admitted())void hydrate();else clearStatusPoll();},5000);}
    async function hydrate(){if(!admitted()){clearStatusPoll();return false;}try{const data=await getJson('/api/backblaze/status');state.data=data;const buckets=data?.buckets||[];if(!state.bucket && buckets.length)state.bucket=buckets[0].bucket;if(state.bucket&&!buckets.some(b=>b.bucket===state.bucket))state.bucket=buckets[0]?.bucket||null;const overall=data?.running?'RUNNING':(data?.last_run_ok===true?'GOOD':(data?.last_run_ok===false?'FAILED':'IDLE'));el('[data-backblaze-state]').textContent=overall;el('[data-backblaze-last]').textContent=data?.last_run_at?new Date(data.last_run_at*1000).toLocaleString():'Never';el('[data-backblaze-duration]').textContent='duration unavailable';el('[data-backblaze-next]').textContent='Not scheduled';renderBuckets();renderSelected();scheduleStatusPoll();return true;}catch(_){el('[data-backblaze-state]').textContent='FAILED';clearStatusPoll();return false;}}
    function hydrateBackblaze(){return hydrate();}
    function secretInput(label){return new Promise(resolve=>{const wrap=document.createElement('div');wrap.className='backblaze-secret-dialog';wrap.innerHTML=`<div class="backblaze-secret-card"><label>${esc(label)}<input type="password" autocomplete="new-password"></label><div><button type="button" data-cancel>Cancel</button><button type="button" data-submit>Continue</button></div></div>`;document.body.append(wrap);const input=wrap.querySelector('input');input.focus();wrap.querySelector('[data-cancel]').onclick=()=>{wrap.remove();resolve('');};wrap.querySelector('[data-submit]').onclick=()=>{const value=input.value;input.value='';wrap.remove();resolve(value);};});}
    async function addBucket(){const bucket=prompt('B2 bucket name');if(!bucket)return;const keyId=prompt('B2 key ID');if(!keyId)return;const applicationKey=await secretInput('B2 application key');if(!applicationKey)return;const body=await getJson('/api/backblaze/buckets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bucket,prefix:'',encrypted:true,items:[],managers:{forgejo:{localNas:false,backblazeBackup:false}},keyId,applicationKey})});el('[data-backblaze-result]').textContent=body.ok===false?(body.reason||'Bucket could not be added'):'Bucket added and verified';await hydrate();}
    async function updateCredentials(){const b=state.data?.buckets?.find(x=>x.bucket===state.bucket);if(!b)return;const keyId=prompt('B2 key ID');if(!keyId)return;const applicationKey=await secretInput('B2 application key');if(!applicationKey)return;const body=await getJson('/api/backblaze/buckets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bucket:b.bucket,prefix:b.prefix||'',encrypted:b.encrypted===true,items:b.items||[],managers:b.managers||{forgejo:{localNas:false,backblazeBackup:false}},keyId,applicationKey})});el('[data-backblaze-result]').textContent=body.ok===false?(body.reason||'Credentials could not be updated'):'Credentials updated and verified';await hydrate();}
    async function verifyBucket(bucket=state.bucket){if(!bucket)return;const body=await getJson('/api/backblaze/buckets/'+encodeURIComponent(bucket)+'/verify',{method:'POST'});const b=state.data?.buckets?.find(x=>x.bucket===bucket);if(b&&typeof body.connected==='boolean')b.connected=body.connected;renderBuckets();renderSelected();el('[data-backblaze-result]').textContent=body.ok===false?(body.reason||'Connection verification failed'):(body.connected===true?'Connected':'Not connected');}
    async function removeBucket(bucket){if(!confirm(`Remove ${bucket}?`))return;await getJson('/api/backblaze/buckets/'+encodeURIComponent(bucket),{method:'DELETE'});if(state.bucket===bucket)state.bucket=null;await hydrate();}
    async function mutateItem(path,method){if(!state.bucket)return;await getJson('/api/backblaze/buckets/'+encodeURIComponent(state.bucket)+'/items',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({path})});await hydrate();}
    async function saveConfig(){const b=state.data?.buckets?.find(x=>x.bucket===state.bucket);if(!b)return;const body=await getJson('/api/backblaze/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({buckets:state.data.buckets.map(x=>({bucket:x.bucket,prefix:x.prefix||'',encrypted:x.encrypted===true,items:Array.isArray(x.items)?x.items:[],managers:state.managerDrafts[x.bucket]?{...(x.managers||{}),forgejo:state.managerDrafts[x.bucket]}:(x.managers||{forgejo:{localNas:false,backblazeBackup:false}})}))})});el('[data-backblaze-result]').textContent=body.ok?'Config saved without credentials':(body.reason||'Config could not be saved');if(body.ok&&await hydrate()){state.managerDrafts={};renderSelected();}}
    function openManager(){const b=state.data?.buckets?.find(x=>x.bucket===state.bucket);if(!b)return;managerDraftBucket=b.bucket;managerDraftBeforeOpen=Object.prototype.hasOwnProperty.call(state.managerDrafts,b.bucket)?{...state.managerDrafts[b.bucket]}:null;const m=state.managerDrafts[b.bucket]||forgejo(b);state.managerDrafts[b.bucket]={localNas:m.localNas===true,backblazeBackup:m.backblazeBackup===true};el('[data-backblaze-local-nas]').checked=state.managerDrafts[b.bucket].localNas;el('[data-backblaze-forgejo-backup]').checked=state.managerDrafts[b.bucket].backblazeBackup;renderManager(b);el('[data-backblaze-manager-modal]').hidden=false;}
    function closeManager(save){const b=state.data?.buckets?.find(x=>x.bucket===managerDraftBucket);if(!save&&managerDraftBucket!==null){if(managerDraftBeforeOpen)state.managerDrafts[managerDraftBucket]={...managerDraftBeforeOpen};else delete state.managerDrafts[managerDraftBucket];}if(b)renderManager(b);el('[data-backblaze-manager-modal]').hidden=true;managerDraftBucket=null;managerDraftBeforeOpen=null;}
    document.body.addEventListener('click',e=>{const v=e.target.closest('[data-backblaze-view]');if(v)setView(v.dataset.backblazeView);if(e.target.closest('[data-backblaze-add]'))void addBucket();if(e.target.closest('[data-backblaze-save]'))void saveConfig();if(e.target.closest('[data-backblaze-verify]'))void verifyBucket();if(e.target.closest('[data-backblaze-update]'))void updateCredentials();if(e.target.closest('[data-backblaze-manager-open]'))openManager();if(e.target.closest('[data-backblaze-manager-cancel]'))closeManager(false);if(e.target.closest('[data-backblaze-manager-close]'))closeManager(true);if(e.target.closest('[data-backblaze-item-add]')){const p=el('[data-backblaze-path]').value.trim();if(p)void mutateItem(p,'POST');}if(e.target.closest('[data-backblaze-run]')&&state.bucket)getJson('/api/backblaze/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bucket:state.bucket})}).then(hydrate);});
    document.body.addEventListener('change',e=>{const b=state.data?.buckets?.find(x=>x.bucket===state.bucket);if(!b)return;if(e.target.matches('[data-backblaze-encrypted]')){void getJson('/api/backblaze/buckets/'+encodeURIComponent(b.bucket)+'/toggle',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({encrypted:e.target.checked})}).then(()=>hydrate());}if(e.target.matches('[data-backblaze-local-nas]')||e.target.matches('[data-backblaze-forgejo-backup]')){const current=state.managerDrafts[b.bucket]||forgejo(b);state.managerDrafts[b.bucket]={...current,localNas:el('[data-backblaze-local-nas]').checked,backblazeBackup:el('[data-backblaze-forgejo-backup]').checked};renderManager(b);}});
    setView('buckets');if (typeof viewportFamilyAdmitted === 'function') void hydrate();
"####
}
