fn shell_dhcp_client() -> &'static str {
    r####"    // The identity binding is the root object: one MAC-keyed roster feeds both perspectives.
    const identityState = { roster: [], boundary: {}, leases: [], reservations: [], dns: {}, modalMac: null };
    const identityPerspective = Object.freeze({
      address: Object.freeze({ lead: ['MAC', 'Observed lease', 'Declared reservation'], emphasis: 'address' }),
      name: Object.freeze({ lead: ['MAC', 'Names', 'Claim state'], emphasis: 'name' }),
    });
    const identityText = value => String(value ?? '—');
    const identityRows = payload => Array.isArray(payload) ? payload : (payload?.devices || payload?.roster || payload?.data?.devices || []);
    async function identityJson(route, options = {}) { const response = await fetch(route, { cache: 'no-store', headers: options.body ? {'content-type':'application/json'} : {}, ...options }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.first_failing_boundary || body.firstMissingSignal || body.error || `Request failed (${response.status})`); return body; }
    function identityIp(row, key) { return row?.[key]?.ip || '—'; }
    function identityRosterMarkup(row, perspective) { const cfg = identityPerspective[perspective]; const names = (row.dns_names || []).join(', ') || '—'; const marks = (row.mismatches || []).map(identityText).join(', ') || 'None'; const observed = identityIp(row, 'observed_lease'); const declared = identityIp(row, 'declared_reservation'); const lead = perspective === 'name' ? names : `${observed} / ${declared}`; return `<tr data-device-mac="${escapeHtml(row.mac)}" data-roster-emphasis="${cfg.emphasis}"><td><code>${escapeHtml(row.mac)}</code></td><td>${escapeHtml(lead)}</td><td>${escapeHtml(observed)}</td><td>${escapeHtml(declared)}</td><td>${escapeHtml(names)}</td><td>${escapeHtml(row.claim_state || 'unclaimed')}</td><td>${escapeHtml(marks)}</td><td><button type="button" class="ui-button ui-button--primary ui-button--small" data-identity-claim="${escapeHtml(row.mac)}">Claim</button></td></tr>`; }
    // This is deliberately the sole roster renderer; tabs differ only by the perspective argument.
    function renderIdentityRoster(perspective) { document.querySelectorAll(`[data-identity-roster-host][data-identity-perspective="${perspective}"] [data-identity-roster]`).forEach(target => { const cfg = identityPerspective[perspective]; target.innerHTML = `<table class="identity-roster"><thead><tr><th>${cfg.lead[0]}</th><th>${cfg.lead[1]}</th><th>Observed lease</th><th>Declared reservation</th><th>DNS names</th><th>${cfg.lead[2]}</th><th>Mismatches</th><th>Action</th></tr></thead><tbody>${identityState.roster.map(row => identityRosterMarkup(row, perspective)).join('') || '<tr><td colspan="8">No devices reported.</td></tr>'}</tbody></table>`; }); }
    function nextFreeIp() { const used = new Set([...identityState.leases, ...identityState.reservations].map(row => String(row.ip || row['ip-address'] || row.ipAddress || ''))); const boundary = identityState.boundary?.boundary || identityState.boundary || {}; const start = String(boundary.start || boundary.first || boundary.pool_start || ''); const end = String(boundary.end || boundary.last || boundary.pool_end || ''); const n = ip => ip.split('.').reduce((acc, part) => acc * 256 + Number(part), 0); const dotted = value => [24,16,8,0].map(shift => (value >>> shift) & 255).join('.'); if (!/^\d+(\.\d+){3}$/.test(start) || !/^\d+(\.\d+){3}$/.test(end)) return ''; for (let value=n(start); value<=n(end); value++) { const ip=dotted(value); if (!used.has(ip)) return ip; } return ''; }
    function openIdentityClaim(mac) { const row = identityState.roster.find(item => item.mac === mac); if (!row) return; identityState.modalMac = row.mac; const modal = document.querySelector('[data-identity-claim-modal]'); const body = document.querySelector('[data-identity-claim-body]'); const suggested = nextFreeIp(); const taken = [...new Set([...identityState.leases, ...identityState.reservations].map(row => row.ip || row['ip-address'] || row.ipAddress).filter(Boolean))]; body.innerHTML = `<p>MAC <code>${escapeHtml(row.mac)}</code> is fixed from this roster row.</p><label>Hostname<input class="ui-input ui-input--medium" data-identity-hostname value="${escapeHtml((row.dns_names || [])[0]?.split('.')[0] || '')}"></label><label>Reserved IP <input class="ui-input ui-input--medium" data-identity-ip value="${escapeHtml(suggested)}" placeholder="${escapeHtml(suggested || 'Staff selects automatically')}"></label><p>Suggested next free: <strong>${escapeHtml(suggested || 'staff decides')}</strong></p><p>Taken: ${escapeHtml(taken.join(', ') || 'none')}</p><p data-identity-claim-result aria-live="polite"></p>`; modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); }
    function closeIdentityClaim() { const modal=document.querySelector('[data-identity-claim-modal]'); modal?.classList.remove('open'); modal?.setAttribute('aria-hidden','true'); }
    async function saveIdentityClaim() { const mac = identityState.modalMac; const hostname = document.querySelector('[data-identity-hostname]')?.value.trim(); const ip = document.querySelector('[data-identity-ip]')?.value.trim(); if (!mac || !hostname) return; const payload = ip ? {mac, ip, hostname} : {mac, autoIp:true, hostname}; const result = document.querySelector('[data-identity-claim-result]'); result.textContent='Saving…'; try { const receipt=await identityJson('/api/network/device/claim',{method:'POST',body:JSON.stringify(payload)}); const state=receipt.state || receipt.data?.state; const boundary=receipt.first_failing_boundary || receipt.data?.first_failing_boundary; result.textContent=(state === 'applied' || state === 'noop') ? (state === 'noop' ? 'Already current.' : 'Applied.') : `${state || 'blocked'}${boundary ? `: ${boundary}` : ''}`; if (state === 'applied' || state === 'noop') { showCoronatioToast(state === 'noop' ? 'Device already current.' : 'Device claim applied.', 'success'); await hydrateIdentity(); } else showCoronatioToast(result.textContent, 'error'); } catch (failure) { result.textContent=`blocked: ${failure.message}`; showCoronatioToast(result.textContent,'error'); } }
    function hydrateDhcp() { return hydrateIdentity(); }
    async function hydrateIdentity() { if (!viewportFamilyAdmitted('dhcp') && !viewportFamilyAdmitted('unbound')) return; try { const [roster,boundary,leases,reservations,dns]=await Promise.all([identityJson('/api/network/device'),identityJson('/api/network/dhcp/boundary'),identityJson('/api/network/dhcp/leases'),identityJson('/api/network/dhcp/reservations'),identityJson('/api/network/dns/read')]); identityState.roster=identityRows(roster); identityState.boundary=boundary; identityState.leases=identityRows(leases); identityState.reservations=identityRows(reservations); identityState.dns=dns; renderIdentityRoster('address'); renderIdentityRoster('name'); renderDnsNames(); const loading=document.querySelector('[data-dhcp-loading]'); if (loading) loading.hidden=true; } catch (failure) { const error=document.querySelector('[data-dhcp-error]'); if(error) {error.hidden=false;error.textContent=`Network identity unavailable: ${failure.message}`;} }
    function renderDnsNames() { const target=document.querySelector('[data-dns-names]'); if (!target) return; const aliases=identityState.dns.aliases || identityState.dns.cnames || []; target.innerHTML=`<h3>Names</h3><p>Device A/PTR rows are projections; claim changes them.</p><ul>${aliases.map(item=>`<li>${escapeHtml(item.name || item.alias || '')} → ${escapeHtml(item.target || item.cname || '')}</li>`).join('') || '<li>No DNS-only aliases.</li>'}</ul><button type="button" class="ui-button ui-button--secondary ui-button--small" disabled title="Alias write route is not available">Alias editing unavailable: Caduceus route pending</button>`; }
    document.addEventListener('click', event => { const claim=event.target.closest?.('[data-identity-claim]'); if(claim) return openIdentityClaim(claim.dataset.identityClaim); if(event.target.closest?.('[data-identity-claim-cancel]')) return closeIdentityClaim(); if(event.target.closest?.('[data-identity-claim-save]')) return saveIdentityClaim(); if(event.target.closest?.('[data-dhcp-refresh],[data-dns-refresh]')) return hydrateIdentity(); },true);
"####
}
