fn shell_firewall_client() -> &'static str {
    r####"    const firewallState = { observed: [], children: [], selectedMac: '', hosts: [], revision: undefined };
    function firewallRows(payload, key) { if (Array.isArray(payload)) return payload; for (const source of [payload?.[key], payload?.devices, payload?.device?.whitelist, payload?.receipt?.[key], payload?.receipt?.devices, payload?.receipt?.device?.whitelist, payload?.data?.[key], payload?.result?.[key], payload?.items]) if (Array.isArray(source)) return source; return []; }
    function firewallMac(row) { return String(row?.mac || row?.macAddress || row?.['hw-address'] || row?.hwAddress || row || '').toUpperCase(); }
    function firewallMessage(payload) { return payload?.message || payload?.firstMissingSignal || payload?.error || 'Child-device controls are unavailable'; }
    async function firewallJson(route, options = {}) { const response = await fetch(route, { cache: 'no-store', headers: options.body ? { 'content-type': 'application/json' } : {}, ...options }); const body = await response.json().catch(() => ({})); if (!response.ok || body?.ok === false) throw body; return body; }
    function renderFirewall() {
      const observed = document.querySelector('[data-firewall-observed]'); const children = document.querySelector('[data-firewall-children]');
      if (observed) observed.innerHTML = firewallState.observed.map(row => { const mac = firewallMac(row); const registered = row?.registered === true || firewallState.children.some(child => firewallMac(child) === mac); return `<li><code>${escapeHtml(mac)}</code><button type="button" class="ui-button ui-button--primary ui-button--small" data-firewall-register="${escapeHtml(mac)}" ${registered ? 'disabled' : ''}>${registered ? 'Registered' : 'Register child device'}</button></li>`; }).join('') || '<li>No observed MAC addresses are available.</li>';
      if (children) children.innerHTML = firewallState.children.map(row => { const mac = firewallMac(row); return `<li><code>${escapeHtml(mac)}</code><div><button type="button" class="ui-button ui-button--secondary ui-button--small" data-firewall-whitelist="${escapeHtml(mac)}">Website whitelist</button><button type="button" class="ui-button ui-button--danger ui-button--small" data-firewall-unregister="${escapeHtml(mac)}">Unregister</button></div></li>`; }).join('') || '<li>No child devices are registered.</li>';
    }
    async function hydrateFirewall() {
      const tablet = document.querySelector('[data-firewall-tablet]'); if (!tablet || !viewportFamilyAdmitted('firewall')) return;
      const error = document.querySelector('[data-firewall-error]'); if (error) error.hidden = true;
      try { const [observed, children] = await Promise.all([firewallJson('/api/firewall/observed'), firewallJson('/api/firewall/children')]); firewallState.observed = firewallRows(observed, 'observed'); firewallState.children = firewallRows(children, 'children'); renderFirewall(); }
      catch (failure) { if (error) { error.hidden = false; error.textContent = firewallMessage(failure); } }
    }
    function firewallPaneElement() { return document.querySelector('[data-pane-panel="firewall"]'); }
    function firewallModalElement() { return firewallPaneElement()?.querySelector('[data-firewall-modal-backdrop]') || null; }
    function closeFirewallModal() { const modal = firewallModalElement(); if (modal) { modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); } }
    async function openFirewallModal(mac) {
      try { const payload = await firewallJson(`/api/firewall/children/${encodeURIComponent(mac)}/whitelist`); const pane = firewallPaneElement(); const modal = firewallModalElement(); const title = pane?.querySelector('[data-firewall-modal-title]'); if (!pane || !modal || !title) throw new Error('Firewall modal is unavailable'); firewallState.selectedMac = mac; firewallState.hosts = firewallRows(payload, 'hostnames'); firewallState.revision = payload.revision; title.textContent = `Website whitelist — ${mac}`; renderFirewallHosts(pane); modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); pane.querySelector('[data-firewall-host-input]')?.focus(); }
      catch (failure) { showCoronatioToast(firewallMessage(failure), 'error'); }
    }
    function renderFirewallHosts(pane = firewallPaneElement()) { const target = pane?.querySelector('[data-firewall-hosts]'); if (target) target.innerHTML = firewallState.hosts.map(host => `<li><code>${escapeHtml(host)}</code><button type="button" class="ui-button ui-button--secondary ui-button--small" data-firewall-remove-host="${escapeHtml(host)}">Remove</button></li>`).join('') || '<li>No websites allowed yet.</li>'; }
    document.body.addEventListener('submit', async event => { const pane = firewallPaneElement(); const form = event.target.closest?.('[data-firewall-host-form]'); if (!pane || !form || !pane.contains(form)) return; event.preventDefault(); const input = form.querySelector('[data-firewall-host-input]'); const host = String(input?.value || '').trim().toLowerCase().replace(/\.$/, ''); if (!host || firewallState.hosts.includes(host)) return; firewallState.hosts.push(host); input.value = ''; renderFirewallHosts(pane); });
    document.addEventListener('click', async event => {
      const pane = firewallPaneElement(); if (!pane || !pane.contains(event.target)) return;
      const control = selector => { const match = event.target.closest?.(selector); return match && pane.contains(match) ? match : null; };
      const modal = firewallModalElement();
      if (event.target === modal || control('[data-firewall-modal-cancel]')) return closeFirewallModal();
      if (control('[data-firewall-refresh]')) return hydrateFirewall();
      const register = control('[data-firewall-register]'); if (register) { try { const receipt = await firewallJson('/api/firewall/children', { method: 'POST', body: JSON.stringify({ mac: register.dataset.firewallRegister }) }); const message = receipt.message || 'Child device registered'; showCoronatioToast(receipt.pinned?.ip ? `${message} (${receipt.pinned.ip})` : message, 'success'); await hydrateFirewall(); } catch (failure) { showCoronatioToast(firewallMessage(failure), 'error'); } return; }
      const unregister = control('[data-firewall-unregister]'); if (unregister) { try { const receipt = await firewallJson(`/api/firewall/children/${encodeURIComponent(unregister.dataset.firewallUnregister)}`, { method: 'DELETE' }); showCoronatioToast(receipt.message || 'Child device unregistered', 'success'); await hydrateFirewall(); } catch (failure) { showCoronatioToast(firewallMessage(failure), 'error'); } return; }
      const whitelist = control('[data-firewall-whitelist]'); if (whitelist) return openFirewallModal(whitelist.dataset.firewallWhitelist);
      const remove = control('[data-firewall-remove-host]'); if (remove) { firewallState.hosts = firewallState.hosts.filter(host => host !== remove.dataset.firewallRemoveHost); return renderFirewallHosts(pane); }
      if (control('[data-firewall-modal-save]')) { const currentModal = firewallModalElement(); const receiptTarget = pane.querySelector('[data-firewall-receipt]'); if (!currentModal || !currentModal.contains(control('[data-firewall-modal-save]')) || !receiptTarget) { showCoronatioToast('Firewall dialog is unavailable', 'error'); return; } try { const receipt = await firewallJson(`/api/firewall/children/${encodeURIComponent(firewallState.selectedMac)}/whitelist`, { method: 'PUT', body: JSON.stringify({ hostnames: firewallState.hosts, expectedRevision: firewallState.revision }) }); const currentPane = firewallPaneElement(); const activeModal = firewallModalElement(); const activeReceipt = currentPane?.querySelector('[data-firewall-receipt]'); if (!activeModal || !activeReceipt) { showCoronatioToast('Whitelist saved, but the Firewall view changed before its receipt could be displayed.', 'success'); return; } activeReceipt.textContent = JSON.stringify(receipt, null, 2); showCoronatioToast(receipt.message || 'Website whitelist saved', 'success'); closeFirewallModal(); } catch (failure) { showCoronatioToast(firewallMessage(failure), 'error'); } }
    }, true);
"####
}
