fn render_test_animations() -> String {
    r#"<section class="test-panel test-animations" data-tab-panel="animations" data-catalog-specimen="indranet-animation-lab" data-animation-lab>
<header class="test-subpanel-header"><div><p class="test-kicker">IndraNet Animation Lab</p><h3>Animations</h3><p>Motion primitives proven here before they reflect through crown panes.</p></div><button type="button" class="ui-button ui-button--secondary" data-motion-stillness>Stillness</button></header>
<section class="animation-band" data-animation-band="atoms"><header><h3>Band A — Motion Atoms</h3><p>Small, explicit transitions. Each specimen moves only when played.</p></header><div class="animation-grid">
<article class="animation-specimen motion-fade"><h4>Fade in / out</h4><div class="motion-stage"><span class="motion-jewel">Fade</span></div><button class="ui-button" data-animation-play>Play</button></article>
<article class="animation-specimen motion-slide"><h4>Slide up / down</h4><div class="motion-stage"><span class="motion-jewel">Slide</span></div><button class="ui-button" data-animation-play>Play</button></article>
<article class="animation-specimen motion-scale"><h4>Scale presence</h4><div class="motion-stage"><span class="motion-jewel">Scale</span></div><button class="ui-button" data-animation-play>Play</button></article>
<article class="animation-specimen motion-color"><h4>Color crossfade</h4><div class="motion-stage"><span class="motion-jewel">Color</span></div><button class="ui-button" data-animation-play>Play</button></article>
<article class="animation-specimen motion-height"><h4>Height collapse / expand</h4><div class="motion-stage"><span class="motion-jewel">Height</span></div><button class="ui-button" data-animation-play>Play</button></article>
</div></section>
<section class="animation-band" data-animation-band="composed"><header><h3>Band B — Composed Motion</h3><p>Reusable reflections raise cards while their stage keeps hit geometry fixed.</p></header><div class="animation-grid">
<article class="animation-specimen" data-hover-specimen><h4>Button hover / press</h4><div class="motion-stage"><button class="ui-button ui-button--primary motion-button">Hover me</button></div></article>
<article class="animation-specimen" data-hover-specimen data-animation-catalog-id="MOTION-TRANCH-01"><h4>Stable-stage raise — MOTION-TRANCH-01</h4><p>REST → ENTER (pointer/focus on stage) → HOLD → EXIT → REST. The child rises 3px with calm depth/glimmer while the stage hit box and status border identity stay fixed; interruption or Stillness restores REST.</p><div class="motion-card-stage" tabindex="0"><div class="portal-card motion-card"><strong>Fixed stage</strong><span>Raise + depth/glimmer</span></div></div><button class="ui-button" data-animation-play>Play / Stillness</button></article>
<article class="animation-specimen"><h4>Toggle slider travel</h4><div class="motion-stage"><div class="motion-toggle" role="switch" aria-checked="false"><span></span></div></div><button class="ui-button" data-animation-play>Play</button></article>
<article class="animation-specimen"><h4>Modal fade + scale</h4><div class="motion-modal-stage"><div class="motion-backdrop"><div class="motion-dialog">Dialog</div></div></div><button class="ui-button" data-animation-play>Play</button></article>
<article class="animation-specimen"><h4>Toast enter / exit</h4><div class="motion-stage"><div class="ui-card motion-toast">Settings saved</div></div><button class="ui-button" data-animation-play>Play</button></article>
<article class="animation-specimen"><h4>Progress stripe</h4><div class="motion-stage"><div class="motion-progress"><span></span></div></div><button class="ui-button" data-animation-play>Start demo</button></article>
<article class="animation-specimen"><h4>Spinner / indicator</h4><div class="motion-stage"><div class="motion-spinner" aria-label="Demo indicator"></div></div><button class="ui-button" data-animation-play>Start demo</button></article>
</div></section>
<section class="animation-band" data-animation-band="lifecycle"><header><h3>Band C — Yijing Lifecycle</h3><p>REST → ENTER → HOLD → EXIT → REST</p></header><article class="motion-lifecycle" data-motion-lifecycle data-motion-phase="REST"><div class="motion-phase">Phase: <strong data-motion-phase-readback>REST</strong></div><div class="motion-stage"><span class="motion-jewel motion-lifecycle-jewel">Jewel</span></div><button class="ui-button" data-animation-play>Run lifecycle</button></article></section>
<section class="animation-band" data-animation-band="accessibility"><header><h3>Band D — Accessibility</h3><p>Compare ordinary motion with the reduced-motion result.</p></header><div class="motion-reduce-row"><article class="animation-specimen motion-slide"><h4>Normal</h4><div class="motion-stage"><span class="motion-jewel">Move</span></div><button class="ui-button" data-animation-play>Play</button></article><article class="animation-specimen motion-slide motion-reduced-preview" data-motion-reduce-preview><h4>Reduced motion</h4><div class="motion-stage"><span class="motion-jewel">Settle</span></div><button class="ui-button" data-animation-play>Play</button></article></div></section>
</section>"#.to_string()
}
