#[derive(Clone, Copy)]
struct UxComponentSpec {
    id: &'static str,
    category: &'static str,
    title: &'static str,
    primitive: &'static str,
    description: &'static str,
    sample: &'static str,
}

fn ux_component_registry() -> Vec<UxComponentSpec> {
    vec![
        UxComponentSpec { id: "button-primary", category: "buttons", title: "Primary Button", primitive: "ux-button", description: "Default action button; uses primary/primaryHover, never status-success.", sample: r#"<div class="ux-row"><button class="ux-button primary">Primary Button</button><button class="ux-button primary">With Icon</button><button class="ux-button primary" aria-busy="true">Loading</button><button class="ux-button primary ux-disabled" disabled>Disabled</button></div>"# },
        UxComponentSpec { id: "button-secondary", category: "buttons", title: "Secondary Button", primitive: "ux-button secondary", description: "Low-emphasis action button.", sample: r#"<div class="ux-row"><button class="ux-button secondary">Secondary Button</button><button class="ux-button secondary">Icon Right ›</button></div>"# },
        UxComponentSpec { id: "button-semantic", category: "buttons", title: "Semantic Buttons", primitive: "ux-button.{danger,warning,success}", description: "Semantic actions are explicit; green appears only on success.", sample: r#"<div class="ux-row"><button class="ux-button danger">Danger Button</button><button class="ux-button warning">Warning Button</button><button class="ux-button success">Success Button</button></div>"# },
        UxComponentSpec { id: "button-sizes", category: "buttons", title: "Button Sizes", primitive: "ux-button small/large", description: "Shared size scale for all future action rows.", sample: r#"<div class="ux-row"><button class="ux-button small">Small</button><button class="ux-button">Medium</button><button class="ux-button large">Large</button></div>"# },
        UxComponentSpec { id: "toggle-basic", category: "toggles", title: "Toggle Switches", primitive: "ux-toggle", description: "On/off state with accessible native input.", sample: r#"<div class="ux-grid"><label class="ux-toggle"><input type="checkbox"> Small Toggle</label><label class="ux-toggle"><input type="checkbox" checked> Medium Toggle</label><label class="ux-toggle"><input type="checkbox" checked disabled> Disabled On</label><label class="ux-toggle"><input type="checkbox" aria-label="Toggle without label"></label></div>"# },
        UxComponentSpec { id: "tabs-plain", category: "tabs", title: "Plain Tabs", primitive: "ux-tabs / ux-tab", description: "Ordinary navigation tabs with no favorite or visibility affordance.", sample: r#"<div class="ux-card" data-ux-tab-affordance="plain"><h4>Plain tab strip</h4><div class="ux-tabs ux-tab-strip"><button class="ux-tab active" aria-selected="true">Overview</button><button class="ux-tab" aria-selected="false">Stats</button><button class="ux-tab" aria-selected="false">Files</button><button class="ux-tab" aria-selected="false" disabled>Disabled</button></div></div>"# },
        UxComponentSpec { id: "tabs-favorite", category: "tabs", title: "Favorite Tabs", primitive: "ux-tab + ux-tab-star", description: "Tabs can carry a star affordance when the surface supports choosing the favorite/default tab.", sample: r#"<div class="ux-card" data-ux-tab-affordance="favorite"><h4>Favorite tab strip</h4><div class="ux-tabs ux-tab-strip ux-tab-strip-favorite"><button class="ux-tab active" aria-selected="true"><span>Upload</span><span class="ux-tab-star" aria-label="favorite tab">★</span></button><button class="ux-tab" aria-selected="false"><span>Portals</span><span class="ux-tab-star muted" aria-label="mark favorite">☆</span></button><button class="ux-tab" aria-selected="false"><span>Stats</span><span class="ux-tab-star muted" aria-label="mark favorite">☆</span></button></div></div>"# },
        UxComponentSpec { id: "tabs-favorite-visibility", category: "tabs", title: "Favorite + Visibility Tabs", primitive: "ux-tab + ux-tab-star + ux-tab-eye", description: "Admin tab rows combine favorite stars with an eyeball affordance for hiding, showing, and faded hidden state without deleting the tab.", sample: r#"<div class="ux-card" data-ux-tab-affordance="favorite-visibility"><h4>Favorite + hide/fade strip</h4><div class="ux-tabs ux-tab-strip ux-tab-strip-managed"><button class="ux-tab active" aria-selected="true"><span>Portals</span><span class="ux-tab-star" aria-label="favorite tab">★</span><span class="ux-tab-eye" aria-label="visible tab">👁</span></button><button class="ux-tab" aria-selected="false"><span>Stats</span><span class="ux-tab-star muted" aria-label="mark favorite">☆</span><span class="ux-tab-eye" aria-label="visible tab">👁</span></button><button class="ux-tab ux-tab-faded" aria-selected="false" data-hidden-tab="true"><span>Admin</span><span class="ux-tab-star muted" aria-label="mark favorite">☆</span><span class="ux-tab-eye muted" aria-label="hidden tab">◌</span></button></div></div>"# },
        UxComponentSpec { id: "input-basic", category: "inputs", title: "Input Fields", primitive: "ux-field", description: "Text, password, read-only, and validation states.", sample: r#"<div class="ux-grid"><label>Username<input class="ux-field" placeholder="Enter username"></label><label>Email with error<input class="ux-field" value="ab" aria-invalid="true"><span class="error">Input must be at least 3 characters</span></label><label>Password<input class="ux-field" type="password" placeholder="Enter password"></label><label>Display<input class="ux-field" value="homeserver" readonly></label></div>"# },
        UxComponentSpec { id: "card-variants", category: "cards", title: "Cards", primitive: "ux-card", description: "Default, header, clickable, active, and error card states.", sample: r#"<div class="ux-grid"><div class="ux-card">Default card body content.</div><div class="ux-card"><h4>Card Header</h4><p>Card body content goes here.</p></div><button type="button" class="ux-card ux-card-button clickable"><strong>Clickable card</strong><span> opens a focused action or drill-in</span></button><div class="ux-card active"><strong>Active card</strong><span> selected persistent state</span></div><div class="ux-card error">Error card</div></div>"# },
        UxComponentSpec { id: "badge-variants", category: "badges", title: "Badges", primitive: "ux-badge / ux-badge-button", description: "Readable status badges plus focusable chip buttons for interactive filters and state picks.", sample: r#"<div class="ux-stack"><div class="ux-row"><span class="ux-badge primary">Primary</span><span class="ux-badge secondary">Secondary</span><span class="ux-badge success">Success</span><span class="ux-badge warning">Warning</span><span class="ux-badge danger">Danger</span><span class="ux-badge info">Info</span></div><div class="ux-row" aria-label="Interactive badge buttons"><button type="button" class="ux-badge ux-badge-button primary" aria-pressed="true">Selected</button><button type="button" class="ux-badge ux-badge-button secondary">Filter</button><button type="button" class="ux-badge ux-badge-button info">Inspect</button></div></div>"# },
        UxComponentSpec { id: "checkbox-variants", category: "checkboxes", title: "Checkboxes", primitive: "ux-checkbox", description: "Checked, unchecked, disabled, and disabled checked states.", sample: r#"<div class="ux-grid"><label class="ux-checkbox"><input type="checkbox" checked> Checked checkbox</label><label class="ux-checkbox"><input type="checkbox"> Unchecked checkbox</label><label class="ux-checkbox"><input type="checkbox" disabled> Disabled unchecked</label><label class="ux-checkbox"><input type="checkbox" checked disabled> Disabled checked</label></div>"# },
        UxComponentSpec { id: "utility-row", category: "utilities", title: "Utility Controls", primitive: "ux-row / ux-breadcrumbs", description: "Icon buttons, editable fields, breadcrumb rows, and focusable cards share one interactable grammar.", sample: r#"<div class="ux-grid"><button class="ux-button small" aria-label="Visibility toggle">👁</button><button class="ux-button small">＋</button><div class="ux-card">Editable field <input class="ux-field" value="editable value"></div><div class="ux-breadcrumbs"><span>/mnt</span><span>›</span><span>nas</span><span>›</span><strong>media</strong></div></div>"# },
        UxComponentSpec { id: "calendar-time", category: "calendar-time", title: "Calendar & Time", primitive: "ux-select / ux-field", description: "Weekly, monthly, and time picker grammar.", sample: r#"<div class="ux-grid"><label>Weekly day<select class="ux-select"><option>Monday</option><option>Friday</option></select></label><label>Monthly day<input class="ux-field" type="number" value="15"></label><label>Time<input class="ux-field" type="time" value="03:00"></label></div>"# },
        UxComponentSpec { id: "row-info-tile", category: "row-info-tile", title: "Row Info Tile", primitive: "ux-cardlet + ux-row", description: "Compact row cardlet for device or service state with hover lift, touch press, and subtle glimmer.", sample: r#"<div class="ux-grid"><button type="button" class="ux-cardlet"><div class="ux-row"><strong>Device A</strong><span class="ux-badge success">Online</span></div><p>Service A · healthy</p></button><button type="button" class="ux-cardlet"><div class="ux-row"><strong>Backup Device</strong><span class="ux-badge warning">Pending</span></div><p>Awaiting next sync window.</p></button></div>"# },
        UxComponentSpec { id: "dropdowns", category: "dropdowns", title: "Dropdowns", primitive: "ux-select", description: "Selection controls that inherit theme and focus tokens.", sample: r#"<div class="ux-grid"><label>Device<select class="ux-select"><option>Device A</option><option>Device B</option></select></label><label>Strategy<select class="ux-select"><option>Safe apply</option><option>Dry run</option></select></label></div>"# },
        UxComponentSpec { id: "slider", category: "slider", title: "Slider", primitive: "range + theme accent", description: "Bounded numeric adjustment control.", sample: r#"<div class="ux-grid"><label>Threshold<input type="range" min="0" max="100" value="50"></label><label>Warning level<input type="range" min="0" max="100" value="75"></label></div>"# },
        UxComponentSpec { id: "textbox", category: "textbox", title: "Text Box", primitive: "ux-textbox", description: "Multi-line text/code/log input.", sample: r#"<textarea class="ux-textbox" rows="8">function calculateTotal(items) { return items.reduce((sum, item) => sum + item.price, 0); }</textarea>"# },
        UxComponentSpec { id: "upload-components", category: "upload-components", title: "Upload Components", primitive: "ux-field / drop-zone / ux-breadcrumbs", description: "File input, drop target, and path breadcrumbs.", sample: r#"<div class="ux-grid"><label>File<input class="ux-field" type="file"></label><div class="drop-zone"><strong>Drop zone</strong><p>Choose files for a target directory.</p></div><div class="ux-breadcrumbs"><span>/root</span><span>›</span><span>path</span><span>›</span><strong>uploads</strong></div></div>"# },
        UxComponentSpec { id: "progress-bar", category: "progress-bar", title: "Progress Bar", primitive: "ux-progress", description: "Deterministic progress visualization.", sample: r#"<div class="ux-stack"><div class="ux-progress"><span style="width:25%"></span></div><div class="ux-progress"><span style="width:75%"></span></div></div>"# },
        UxComponentSpec { id: "table-state-actions", category: "tables", title: "State + Action Table", primitive: "ux-table ux-table-actions", description: "A readable appliance table with status badges, aligned actions, row hover, and a contained scroll shell.", sample: r#"<div class="ux-table-shell"><table class="ux-table ux-table-actions"><caption>Service action matrix</caption><thead><tr><th scope="col">Name</th><th scope="col">Status</th><th scope="col">Updated</th><th scope="col">Action</th></tr></thead><tbody><tr><td><strong>Service A</strong><span class="ux-table-subtext">front panel</span></td><td><span class="ux-badge success">Active</span></td><td>now</td><td><button class="ux-button small">Inspect</button></td></tr><tr><td><strong>Membrane</strong><span class="ux-table-subtext">receipt lane</span></td><td><span class="ux-badge warning">Boundary</span></td><td>2m</td><td><button class="ux-button small secondary">Read</button></td></tr><tr><td><strong>Archive</strong><span class="ux-table-subtext">cold path</span></td><td><span class="ux-badge secondary">Idle</span></td><td>1h</td><td><button class="ux-button small secondary">Open</button></td></tr></tbody></table></div>"# },
        UxComponentSpec { id: "table-sort-filter", category: "tables", title: "Sortable / Filterable Table", primitive: "ux-table ux-table-sortable", description: "Column headers expose obvious sort controls while the toolbar carries search and density affordances.", sample: r#"<div class="ux-table-toolbar"><input class="ux-field" value="status:active" aria-label="Filter rows"><button class="ux-button small secondary">Dense</button><button class="ux-button small">Export</button></div><div class="ux-table-shell"><table class="ux-table ux-table-sortable ux-table-dense"><thead><tr><th scope="col"><button class="ux-table-sort" aria-sort="ascending">Device <span>▲</span></button></th><th scope="col"><button class="ux-table-sort">Load <span>↕</span></button></th><th scope="col"><button class="ux-table-sort">Health <span>↕</span></button></th></tr></thead><tbody><tr><td>Device A</td><td><meter min="0" max="100" value="42">42%</meter></td><td><span class="ux-badge success">Ready</span></td></tr><tr><td>Device B</td><td><meter min="0" max="100" value="78">78%</meter></td><td><span class="ux-badge warning">Busy</span></td></tr><tr><td>Device C</td><td><meter min="0" max="100" value="8">8%</meter></td><td><span class="ux-badge secondary">Quiet</span></td></tr></tbody></table></div>"# },
        UxComponentSpec { id: "table-selectable", category: "tables", title: "Selectable Table", primitive: "ux-table ux-table-selectable", description: "Bulk work starts with first-column selection, a selected-row state, and compact row metadata.", sample: r#"<div class="ux-table-shell"><table class="ux-table ux-table-selectable"><thead><tr><th scope="col"><input type="checkbox" aria-label="Select all rows"></th><th scope="col">Artifact</th><th scope="col">Plane</th><th scope="col">Receipt</th></tr></thead><tbody><tr class="ux-row-selected"><td><input type="checkbox" checked aria-label="Select Alpha"></td><td>Alpha</td><td>source</td><td><code>rcpt-ready</code></td></tr><tr><td><input type="checkbox" aria-label="Select Beta"></td><td>Beta</td><td>runtime</td><td><code>pending</code></td></tr></tbody></table></div>"# },
        UxComponentSpec { id: "graph-line-area", category: "graphs", title: "Line / Area Chart", primitive: "ux-chart ux-chart-line", description: "Trend chart frame with title, axes, grid, plotted line, filled area, legend, and last-value readout.", sample: r#"<figure class="ux-chart ux-chart-line" role="img" aria-label="Request trend line chart"><figcaption><strong>Requests</strong><span>last 6 intervals</span></figcaption><svg viewBox="0 0 320 180" class="ux-chart-frame"><g class="ux-chart-grid"><line x1="40" y1="32" x2="300" y2="32"></line><line x1="40" y1="82" x2="300" y2="82"></line><line x1="40" y1="132" x2="300" y2="132"></line></g><g class="ux-chart-axis"><line x1="40" y1="145" x2="300" y2="145"></line><line x1="40" y1="20" x2="40" y2="145"></line><text x="32" y="36">90</text><text x="32" y="86">45</text><text x="32" y="136">0</text></g><polygon class="ux-chart-area" points="40,124 92,112 144,72 196,96 248,58 300,42 300,145 40,145"></polygon><polyline class="ux-chart-line-path" points="40,124 92,112 144,72 196,96 248,58 300,42"></polyline><circle class="ux-chart-point" cx="300" cy="42" r="4"></circle></svg><div class="ux-chart-legend"><span><i></i> Requests</span><strong>88</strong></div></figure>"# },
        UxComponentSpec { id: "graph-bar", category: "graphs", title: "Bar Chart", primitive: "ux-chart ux-chart-bar", description: "Categorical bars with axis frame, value labels, hoverable bar slots, and theme-aware fill colors.", sample: r#"<figure class="ux-chart ux-chart-bar" role="img" aria-label="Capacity bar chart"><figcaption><strong>Capacity</strong><span>per lane</span></figcaption><svg viewBox="0 0 320 180" class="ux-chart-frame"><g class="ux-chart-grid"><line x1="36" y1="42" x2="300" y2="42"></line><line x1="36" y1="92" x2="300" y2="92"></line><line x1="36" y1="142" x2="300" y2="142"></line></g><g class="ux-chart-bars"><rect x="58" y="82" width="34" height="60"></rect><rect x="118" y="54" width="34" height="88"></rect><rect x="178" y="112" width="34" height="30"></rect><rect x="238" y="34" width="34" height="108"></rect></g><g class="ux-chart-labels"><text x="75" y="160">A</text><text x="135" y="160">B</text><text x="195" y="160">C</text><text x="255" y="160">D</text></g></svg><div class="ux-chart-legend"><span><i></i> Used</span><strong>74%</strong></div></figure>"# },
        UxComponentSpec { id: "graph-donut", category: "graphs", title: "Donut / Ratio Chart", primitive: "ux-chart ux-chart-donut", description: "Ratio chart for composition states with center value, legend chips, and accessible text fallback.", sample: r#"<figure class="ux-chart ux-chart-donut" role="img" aria-label="Storage composition donut chart"><figcaption><strong>Storage Mix</strong><span>sample composition</span></figcaption><div class="ux-donut" style="--ux-donut-a: 64%; --ux-donut-b: 82%;"><span>64%</span></div><div class="ux-chart-legend"><span><i></i> Media</span><span><i class="secondary"></i> Backups</span><span><i class="muted"></i> Free</span></div></figure>"# },
        UxComponentSpec { id: "graph-sparkline", category: "graphs", title: "Sparkline Strip", primitive: "ux-sparkline", description: "Compact inline trend primitive for rows, cards, and small status tiles.", sample: r#"<div class="ux-grid"><div class="ux-card"><div class="ux-row"><strong>Latency</strong><span class="ux-badge success">steady</span></div><svg viewBox="0 0 160 44" class="ux-sparkline" role="img" aria-label="Latency sparkline"><polyline points="0,30 24,28 48,32 72,16 96,20 120,12 160,18"></polyline></svg></div><div class="ux-card"><div class="ux-row"><strong>Queue</strong><span class="ux-badge warning">rising</span></div><svg viewBox="0 0 160 44" class="ux-sparkline warning" role="img" aria-label="Queue sparkline"><polyline points="0,34 24,31 48,26 72,25 96,19 120,14 160,8"></polyline></svg></div></div>"# },
        UxComponentSpec { id: "collapsible", category: "collapsible", title: "Collapsible", primitive: "details + ux-card", description: "Disclosure rows for compact evidence.", sample: r#"<details class="ux-card"><summary>Open details</summary><p>Composable details content.</p></details><details class="ux-card" open><summary>Open by default</summary><pre class="ux-readout">receipt: testtab.component.collapsible.v1</pre></details>"# },
        UxComponentSpec { id: "modals", category: "modals", title: "Modals", primitive: "ux-modal-sample / ux-modal-shell.{small,medium,fullscreen}", description: "Launchable modal sizes for compact confirmations, regular dialogs, and full-screen flows.", sample: r#"<div class="ux-stack" data-ux-modal-demo="sizes"><div class="ux-row"><button type="button" class="ux-button small" data-ux-modal-open="small">Open small modal</button><button type="button" class="ux-button" data-ux-modal-open="medium">Open medium modal</button><button type="button" class="ux-button large" data-ux-modal-open="fullscreen">Open fullscreen modal</button></div><div class="ux-modal-gallery" aria-label="Modal size examples"><article class="ux-modal-sample ux-modal-shell small" data-ux-modal-size-sample="small"><h4>Small modal</h4><p>Compact confirm or short choice.</p></article><article class="ux-modal-sample ux-modal-shell medium" data-ux-modal-size-sample="medium"><h4>Medium modal</h4><p>Regular settings or detail dialog.</p></article><article class="ux-modal-sample ux-modal-shell fullscreen" data-ux-modal-size-sample="fullscreen"><h4>Fullscreen modal</h4><p>Focused full-screen workflow.</p></article></div><div class="ux-modal-backdrop" data-ux-modal-demo-backdrop aria-hidden="true"><section class="ux-modal-shell medium" role="dialog" aria-modal="true" aria-labelledby="ux-modal-demo-title" data-ux-modal-demo-window><div class="ux-row"><h4 id="ux-modal-demo-title" data-ux-modal-demo-title>Medium modal</h4><button type="button" class="ux-button small secondary" data-ux-modal-close>Close</button></div><p data-ux-modal-demo-body>Regular dialog body.</p><div class="ux-row"><button type="button" class="ux-button secondary" data-ux-modal-close>Cancel</button><button type="button" class="ux-button">Confirm</button></div></section></div></div>"# },

        UxComponentSpec { id: "theme-gradients", category: "theme-system", title: "Theme Gradients", primitive: "gradient tokens", description: "Gradient tokens are named by intent so skins can become richer without component rewrites.", sample: r#"<div class="ux-grid"><div class="ux-gradient-swatch primary" title="gradient-primary"></div><div class="ux-gradient-swatch accent" title="gradient-accent"></div><div class="ux-gradient-swatch surface" title="gradient-surface"></div><div class="ux-gradient-swatch highlight" title="gradient-highlight"></div></div>"# },
        UxComponentSpec { id: "theme-highlights", category: "theme-system", title: "Highlight Layers", primitive: "highlight tokens", description: "Highlight and state-layer tokens separate attention from success/status color.", sample: r#"<div class="ux-grid"><div class="ux-card ux-highlight-card">Focused highlight card</div><button class="ux-button ux-state-layer">Hover state layer</button><div class="ux-card" style="box-shadow: var(--theme-elevation-2)">Elevation 2 card</div></div>"# },
        UxComponentSpec { id: "theme-accents", category: "theme-system", title: "Accent Families", primitive: "accent tokens", description: "Warm, cool, neutral, and critical accents give visual range while status colors stay truthful.", sample: r#"<div class="ux-stack"><div class="ux-accent-strip"><span></span><span></span><span></span><span></span></div><div class="ux-row"><span class="ux-badge primary">warm</span><span class="ux-badge info">cool</span><span class="ux-badge secondary">neutral</span><span class="ux-badge danger">critical</span></div></div>"# },
        UxComponentSpec { id: "theme-role-pairs", category: "theme-system", title: "Role Pairs", primitive: "role/on-role tokens", description: "Material-style role pairs keep container/on-container contrast explicit.", sample: r#"<div class="ux-grid"><div class="ux-role-pair primary"><strong>role-primary</strong><span>role-on-primary</span></div><div class="ux-role-pair"><strong>surface-1</strong><span>on-surface / outline</span></div></div>"# },
    ]
}

fn title_for_category(category: &str) -> String {
    category
        .split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn ux_component_categories(registry: &[UxComponentSpec]) -> Vec<&'static str> {
    let mut categories = Vec::new();
    for component in registry {
        if !categories.contains(&component.category) {
            categories.push(component.category);
        }
    }
    categories
}

fn render_ux_component_card(component: &UxComponentSpec) -> String {
    format!(
        r#"<article class="ux-card ux-component-card" data-ux-component="{id}" data-ux-category="{category}" data-ux-primitive="{primitive}"><div class="ux-row"><h4>{title}</h4><span class="ux-badge secondary">{primitive}</span></div><p>{description}</p><div class="ux-component-sample">{sample}</div></article>"#,
        id = component.id,
        category = component.category,
        primitive = component.primitive,
        title = component.title,
        description = component.description,
        sample = component.sample
    )
}

fn render_ux_component_showcase(registry: &[UxComponentSpec]) -> String {
    let categories = ux_component_categories(registry);
    let tabs = categories
        .iter()
        .enumerate()
        .map(|(index, category)| {
            format!(
                r#"<button type="button" class="ux-tab {active}" data-showcase-tab="{category}" aria-selected="{selected}">{title}</button>"#,
                active = if index == 0 { "active" } else { "" },
                selected = if index == 0 { "true" } else { "false" },
                category = category,
                title = title_for_category(category)
            )
        })
        .collect::<Vec<_>>()
        .join("");
    let panels = categories
        .iter()
        .enumerate()
        .map(|(index, category)| {
            let cards = registry
                .iter()
                .filter(|component| component.category == *category)
                .map(render_ux_component_card)
                .collect::<Vec<_>>()
                .join("");
            format!(
                r#"<section class="ux-panel {active}" data-showcase-panel="{category}"><div class="ux-row"><h3>{title}</h3><span class="ux-badge primary">{count} component{plural}</span></div><div class="ux-grid">{cards}</div></section>"#,
                active = if index == 0 { "active" } else { "" },
                category = category,
                title = title_for_category(category),
                count = registry.iter().filter(|component| component.category == *category).count(),
                plural = if registry.iter().filter(|component| component.category == *category).count() == 1 { "" } else { "s" },
                cards = cards
            )
        })
        .collect::<Vec<_>>()
        .join("");
    format!(
        r#"<section class="ux-panel active" data-testtab-panel="showcase"><div class="ux-row"><h3>Component Showcase</h3><span class="ux-badge info" data-ux-registry-count>{count} registered UX components</span></div><div class="ux-tabs" role="tablist" aria-label="Component showcase categories" data-showcase-tabs>{tabs}</div><div class="ux-stack" data-showcase-panels>{panels}</div></section>"#,
        count = registry.len(),
        tabs = tabs,
        panels = panels
    )
}

fn render_testtab_theme_values() -> String {
    r#"<section class="ux-panel" data-testtab-panel="theme-values" data-theme-values-panel="true"><article class="ux-card"><div class="ux-row"><h3>Theme Values</h3><span class="ux-badge info">live CSS token map</span></div><p>Theme values show the flat legacy variables and expanded theme-system tokens as visible appliance primitives, including expanded JSON gradient-accent and related role tokens. Buttons use primary roles; status chips use success/warning/error roles; highlights, gradients, elevation, and focus rings are separate attention layers.</p><div class="ux-grid theme-values-grid"><article class="ux-card" data-theme-value-family="core"><h4>Core surface roles</h4><table class="ux-table theme-token-table"><thead><tr><th>Token</th><th>Sample</th><th>Purpose</th></tr></thead><tbody><tr><td><code>--background</code></td><td><span class="theme-chip surface-0">background</span></td><td>page base</td></tr><tr><td><code>--surface</code></td><td><span class="theme-chip surface-1">surface</span></td><td>card body</td></tr><tr><td><code>--text</code></td><td><span class="theme-chip on-surface">text</span></td><td>ordinary copy</td></tr><tr><td><code>--border</code></td><td><span class="theme-chip outline">border</span></td><td>seams and dividers</td></tr></tbody></table></article><article class="ux-card" data-theme-value-family="actions"><h4>Action vs status separation</h4><div class="ux-stack"><button class="ux-button primary">Primary action</button><button class="ux-button secondary">Secondary action</button><div class="ux-row"><span class="ux-badge success">success status</span><span class="ux-badge warning">warning status</span><span class="ux-badge danger">error status</span></div><pre class="ux-readout">button: --primary / --primaryHover
status: --success / --warning / --error</pre></div></article><article class="ux-card" data-theme-value-family="gradients"><h4>Gradients</h4><div class="ux-grid"><div class="ux-gradient-swatch primary" title="--theme-gradient-primary"></div><div class="ux-gradient-swatch accent" title="--theme-gradient-accent"></div><div class="ux-gradient-swatch surface" title="--theme-gradient-surface"></div><div class="ux-gradient-swatch highlight" title="--theme-gradient-highlight"></div></div></article><article class="ux-card" data-theme-value-family="highlights"><h4>Highlights / focus / elevation</h4><div class="ux-grid"><div class="ux-card ux-highlight-card">highlight-subtle + highlight-ring</div><button class="ux-button ux-state-layer">state layer hover</button><div class="ux-card" style="box-shadow: var(--theme-elevation-2)">elevation-2</div><button class="ux-button" style="box-shadow: var(--theme-highlight-ring)">focus ring sample</button></div></article><article class="ux-card" data-theme-value-family="accents"><h4>Accent families</h4><div class="ux-accent-strip"><span></span><span></span><span></span><span></span></div><div class="ux-row"><span class="ux-badge primary">warm</span><span class="ux-badge info">cool</span><span class="ux-badge secondary">neutral</span><span class="ux-badge danger">critical</span></div></article><article class="ux-card" data-theme-value-family="roles"><h4>Role / on-role pairs</h4><div class="ux-grid"><div class="ux-role-pair primary"><strong>--theme-role-primary</strong><span>--theme-role-on-primary</span></div><div class="ux-role-pair"><strong>--theme-surface-1</strong><span>--theme-on-surface / --theme-outline</span></div></div></article></div><table class="ux-table theme-token-table"><thead><tr><th>Family</th><th>Representative variables</th><th>Visible job</th></tr></thead><tbody data-theme-token-readout><tr><td>button roles</td><td><code>--primary</code>, <code>--primaryHover</code>, <code>--theme-component-button-container</code></td><td>interactive controls</td></tr><tr><td>status roles</td><td><code>--success</code>, <code>--warning</code>, <code>--error</code></td><td>truthful state labels only</td></tr><tr><td>attention layers</td><td><code>--theme-highlight-subtle</code>, <code>--theme-highlight-ring</code></td><td>focus and hover emphasis</td></tr><tr><td>shape/rhythm</td><td><code>--theme-radius-pill</code>, <code>--theme-card-padding</code>, <code>--theme-grid-gap</code></td><td>component geometry</td></tr></tbody></table></article></section>"#.to_string()
}

fn render_testtab() -> String {
    let registry = ux_component_registry();
    format!(
        r#"<section class="pane" id="pane-testtab" data-pane-panel="testtab" role="tabpanel" aria-label="TestTab"><div class="test-tablet ux-surface" data-native-stock-testtab="true" data-admin-viewport="testtab" data-react-quarry="premium/testTab" data-ux-library="coronatio-composable-ux.v1" data-ux-registry="rust-native"><div class="ux-tabs" role="tablist" aria-label="TestTab sections" data-testtab-tabs><button type="button" class="ux-tab active" data-testtab-tab="showcase" aria-selected="true">Component Showcase</button><button type="button" class="ux-tab" data-testtab-tab="theme-values" aria-selected="false">Theme Values</button></div><div class="test-tablet-content ux-stack">{showcase}{theme_values}</div></div></section>"#,
        showcase = render_ux_component_showcase(&registry),
        theme_values = render_testtab_theme_values()
    )
}
