const OG_TESTTAB_CATEGORIES: [(&str, &str); 18] = [
    ("buttons", "Buttons"),
    ("toggles", "Toggles"),
    ("tabs", "Tabs"),
    ("inputs", "Inputs"),
    ("cards", "Cards"),
    ("badges", "Badges"),
    ("checkboxes", "Checkboxes"),
    ("utilities", "Utilities"),
    ("calendar-time", "Calendar & Time"),
    ("row-info-tile", "Row Info Tile"),
    ("dropdowns", "Dropdowns"),
    ("slider", "Slider"),
    ("textbox", "Text Box"),
    ("upload-components", "Upload Components"),
    ("progress-bar", "Progress Bar"),
    ("table", "Table"),
    ("collapsible", "Collapsible"),
    ("modals", "Modals"),
];

fn render_category_chip_grid() -> String {
    OG_TESTTAB_CATEGORIES
        .iter()
        .enumerate()
        .map(|(index, (id, title))| {
            format!(
                r#"<button type="button" class="ui-tab {active}" data-tab-id="{id}" data-category-chip="{id}" aria-selected="{selected}" data-depth="3"><span class="ui-tab__content"><span class="ui-tab__label">{title}</span></span></button>"#,
                active = if index == 0 { "ui-tab--active active" } else { "" },
                selected = if index == 0 { "true" } else { "false" },
                id = id,
                title = title
            )
        })
        .collect::<Vec<_>>()
        .join("")
}

fn section(id: &str, title: &str, body: &str, active: bool) -> String {
    format!(
        r#"<section id="showcase-{id}" class="showcase-section {active}" data-tab-panel="{id}" data-og-category-section="{id}"><h3>{title}</h3>{body}</section>"#,
        id = id,
        title = title,
        active = if active { "active" } else { "" },
        body = body
    )
}

fn render_component_showcase() -> String {
    let mut panels = Vec::new();
    panels.push(section("buttons", "Button Variants", r#"
      <div class="showcase-grid">
        <div class="showcase-item"><h4>Primary</h4><button class="ui-button ui-button--primary">Primary Button</button><button class="ui-button ui-button--primary"><span class="ui-button__icon ui-button__icon--left">⌘</span>With Icon</button><button class="ui-button ui-button--primary ui-button--loading" aria-busy="true">Loading</button><button class="ui-button ui-button--primary" disabled>Disabled</button></div>
        <div class="showcase-item"><h4>Secondary</h4><button class="ui-button ui-button--secondary">Secondary Button</button><button class="ui-button ui-button--secondary">Icon Right <span class="ui-button__icon ui-button__icon--right">👤</span></button><button class="ui-button ui-button--secondary" disabled>Disabled</button></div>
        <div class="showcase-item"><h4>Danger</h4><button class="ui-button ui-button--danger">Danger Button</button><button class="ui-button ui-button--danger" disabled>Disabled</button></div>
        <div class="showcase-item"><h4>Warning</h4><button class="ui-button ui-button--warning">Warning Button</button><button class="ui-button ui-button--warning" disabled>Disabled</button></div>
        <div class="showcase-item"><h4>Success</h4><button class="ui-button ui-button--success">Success Button</button><button class="ui-button ui-button--success" disabled>Disabled</button></div>
      </div>
      <h3>Button Sizes</h3><div class="showcase-row"><button class="ui-button ui-button--primary ui-button--small">Small</button><button class="ui-button ui-button--primary ui-button--medium">Medium</button><button class="ui-button ui-button--primary ui-button--large">Large</button></div>
    "#, true));
    panels.push(section("toggles", "Toggle Switches", r#"<div class="showcase-grid"><div class="showcase-item"><h4>Small</h4><label class="ui-toggle ui-toggle--small"><span class="ui-toggle__switch"><input class="ui-toggle__input" type="checkbox" data-ui-toggle><span class="ui-toggle__slider"></span></span><span class="ui-toggle__label">Small Toggle</span></label></div><div class="showcase-item"><h4>Medium (Default)</h4><label class="ui-toggle ui-toggle--medium"><span class="ui-toggle__switch"><input class="ui-toggle__input" type="checkbox" checked data-ui-toggle><span class="ui-toggle__slider"></span></span><span class="ui-toggle__label">Medium Toggle</span></label></div><div class="showcase-item"><h4>Large</h4><label class="ui-toggle ui-toggle--large"><span class="ui-toggle__switch"><input class="ui-toggle__input" type="checkbox" data-ui-toggle><span class="ui-toggle__slider"></span></span><span class="ui-toggle__label">Large Toggle</span></label></div><div class="showcase-item"><h4>Without Label</h4><label class="ui-toggle ui-toggle--medium"><span class="ui-toggle__switch"><input class="ui-toggle__input" type="checkbox" aria-label="Toggle without label" data-ui-toggle><span class="ui-toggle__slider"></span></span></label></div><div class="showcase-item"><h4>Disabled</h4><label class="ui-toggle ui-toggle--medium ui-toggle--disabled"><span class="ui-toggle__switch"><input class="ui-toggle__input" type="checkbox" disabled><span class="ui-toggle__slider"></span></span><span class="ui-toggle__label">Disabled Off</span></label><label class="ui-toggle ui-toggle--medium ui-toggle--disabled"><span class="ui-toggle__switch"><input class="ui-toggle__input" type="checkbox" checked disabled><span class="ui-toggle__slider"></span></span><span class="ui-toggle__label">Disabled On</span></label></div></div>"#, false));
    panels.push(section("tabs", "Tab Navigation", r#"<div class="showcase-item"><h4>Basic Tabs</h4><div class="ui-tab-group"><button class="ui-tab ui-tab--active active"><span class="ui-tab__content">⌘ <span class="ui-tab__label">Home</span></span></button><button class="ui-tab"><span class="ui-tab__content"><span class="ui-tab__label">Profile</span></span></button><button class="ui-tab"><span class="ui-tab__content"><span class="ui-tab__label">Settings</span></span></button><button class="ui-tab" disabled><span class="ui-tab__content"><span class="ui-tab__label">Disabled</span></span></button></div></div><div class="showcase-item"><h4>Visibility States (Admin Mode)</h4><div class="ui-tab-group"><button class="ui-tab ui-tab--active active"><span class="ui-tab__visibility-column">👁</span><span class="ui-tab__content">Visible Tab</span><span class="ui-tab__star-column">★</span></button><button class="ui-tab ui-tab--hidden"><span class="ui-tab__visibility-column">◌</span><span class="ui-tab__content">Hidden Tab</span><span class="ui-tab__star-column">☆</span></button></div></div><div class="showcase-item"><h4>Admin Only Tab</h4><div class="ui-tab-group"><button class="ui-tab ui-tab--admin-only active">Admin Only Tab</button><button class="ui-tab ui-tab--admin-only">Another Admin Only</button></div></div>"#, false));
    panels.push(section("inputs", "Input Fields", r#"<div class="showcase-grid"><div class="showcase-item"><h4>Text Input</h4><label class="ui-input-label">Username<input class="ui-input" type="text" placeholder="Enter username" data-ui-input></label></div><div class="showcase-item"><h4>Input with Error</h4><label class="ui-input-label">Email<input class="ui-input ui-input--error" type="text" value="ab" data-ui-input><span class="ui-input__error">Input must be at least 3 characters</span></label></div><div class="showcase-item"><h4>Password Input</h4><input class="ui-input" type="password" placeholder="Enter password"></div><div class="showcase-item"><h4>Required Field</h4><input class="ui-input" required placeholder="This field is required"></div><div class="showcase-item"><h4>Disabled Input</h4><input class="ui-input" value="Cannot edit" disabled></div><div class="showcase-item"><h4>Display Variant</h4><input class="ui-input ui-input--display" value="homeserver" readonly></div><div class="showcase-item"><h4>Input Sizes</h4><input class="ui-input ui-input--small" placeholder="Small input"><input class="ui-input ui-input--medium" placeholder="Medium input"><input class="ui-input ui-input--large" placeholder="Large input"></div></div>"#, false));
    panels.push(section("cards", "Cards", r#"<div class="showcase-grid"><div class="showcase-item"><h4>Default Card</h4><div class="ui-card"><p>This is a default card with some content.</p></div></div><div class="showcase-item"><h4>Card with Header</h4><div class="ui-card"><div class="ui-card__header">Card Header</div><div class="ui-card__body"><p>Card body content goes here.</p></div></div></div><div class="showcase-item"><h4>Card with Footer</h4><div class="ui-card"><div class="ui-card__body">Card with footer actions.</div><div class="ui-card__footer"><button class="ui-button ui-button--primary ui-button--small">Action</button></div></div></div><div class="showcase-item"><h4>Clickable Card</h4><button class="ui-card ui-card--clickable">Click this card to interact.</button></div><div class="showcase-item"><h4>Active Card</h4><div class="ui-card ui-card--active">This card indicates an active state.</div></div><div class="showcase-item"><h4>Error Card</h4><div class="ui-card ui-card--error">This card indicates an error state.</div></div></div>"#, false));
    panels.push(section("badges", "Badges", r#"<div class="showcase-grid"><div class="showcase-item"><h4>Badge Variants</h4><div class="showcase-row"><span class="ui-badge ui-badge--primary">Primary</span><span class="ui-badge ui-badge--secondary">Secondary</span><span class="ui-badge ui-badge--success">Success</span><span class="ui-badge ui-badge--warning">Warning</span><span class="ui-badge ui-badge--danger">Danger</span><span class="ui-badge ui-badge--info">Info</span></div></div><div class="showcase-item"><h4>Badge Sizes</h4><span class="ui-badge ui-badge--small">Small</span><span class="ui-badge ui-badge--medium">Medium</span><span class="ui-badge ui-badge--large">Large</span></div><div class="showcase-item"><h4>Badge Usage Examples</h4><div>Status: <span class="ui-badge ui-badge--success">Online</span></div><div>Count: <span class="ui-badge ui-badge--primary">42</span></div><div>Alert: <span class="ui-badge ui-badge--danger">Critical</span></div></div></div>"#, false));
    panels.push(section("checkboxes", "Checkboxes", r#"<div class="showcase-grid"><div class="showcase-item"><h4>Basic Checkboxes</h4><label class="ui-checkbox"><input type="checkbox" checked data-ui-checkbox>Checked checkbox</label><label class="ui-checkbox"><input type="checkbox" data-ui-checkbox>Unchecked checkbox</label><label class="ui-checkbox"><input type="checkbox" checked data-ui-checkbox>Another checked</label></div><div class="showcase-item"><h4>Checkbox Sizes</h4><label class="ui-checkbox ui-checkbox--small"><input type="checkbox" checked>Small checkbox</label><label class="ui-checkbox ui-checkbox--medium"><input type="checkbox">Medium checkbox</label><label class="ui-checkbox ui-checkbox--large"><input type="checkbox" checked>Large checkbox</label></div><div class="showcase-item"><h4>Disabled Checkboxes</h4><label class="ui-checkbox"><input type="checkbox" disabled>Disabled unchecked</label><label class="ui-checkbox"><input type="checkbox" checked disabled>Disabled checked</label></div><div class="showcase-item"><h4>Stats Tab Style (Grouped)</h4><div class="device-control"><span class="device-name">nas</span><label class="drive-checkbox"><input type="checkbox" checked>Read</label><label class="drive-checkbox"><input type="checkbox">Write</label></div></div></div>"#, false));
    panels.push(section("utilities", "Utility Components", r#"<div class="showcase-grid"><div class="showcase-item"><h4>Visibility Toggle</h4><button class="visibility-toggle" data-ui-visibility-toggle data-visible="true">👁</button><button class="visibility-toggle" data-ui-visibility-toggle data-visible="false">◌</button></div><div class="showcase-item"><h4>Plus Button</h4><button class="plus-button plus-button--small">+</button><button class="plus-button plus-button--medium">+</button><button class="plus-button plus-button--large">+</button><button class="plus-button" disabled>+</button></div><div class="showcase-item"><h4>Editable Field</h4><span class="editable-field" contenteditable="true">Click to edit this text</span><span class="editable-field editable-field--empty" contenteditable="true">Empty field - click to edit</span><span class="editable-field editable-field--disabled">Disabled field</span></div></div>"#, false));
    panels.push(section("calendar-time", "Calendar & Time Picker", r#"<div class="showcase-grid"><div class="showcase-item"><h4>Calendar - Weekly Mode</h4><select class="calendar-picker" data-ui-calendar><option>Monday</option><option>Tuesday</option><option>Friday</option></select><p class="muted" data-ui-calendar-output></p></div><div class="showcase-item"><h4>Calendar - Monthly Mode</h4><input class="calendar-picker" type="number" min="1" max="31" data-ui-calendar></div><div class="showcase-item"><h4>Time Picker</h4><input class="time-picker" type="time" value="03:00" data-ui-time-picker><p>Selected: <span data-ui-time-output>03:00</span> (24-hour format)</p></div><div class="showcase-item"><h4>Disabled States</h4><input class="calendar-picker" value="Monday" disabled><input class="time-picker" value="09:00" disabled></div></div>"#, false));
    panels.push(section("row-info-tile", "Row Info Tile", r#"<p>A flexible row information tile component for displaying structured data with icons, badges, metadata, and actions.</p><div class="showcase-grid"><div class="row-info-tile"><span>📁</span><strong>Documents</strong><span>Folder</span></div><div class="row-info-tile"><span>📄</span><strong>report.pdf</strong><span class="ui-badge ui-badge--primary">PDF</span><span class="ui-badge ui-badge--info">2.3 MB</span></div><label class="row-info-tile row-info-tile--selected"><input type="checkbox" checked>📁 Old <span class="ui-badge ui-badge--success">Directory</span></label><button class="row-info-tile">📁 Clickable Folder <span>Double-click to open</span></button><div class="row-info-tile row-info-tile--error">⚠️ Error File <span class="ui-badge ui-badge--danger">Error</span></div></div>"#, false));
    panels.push(section("dropdowns", "Click-to-Open Dropdowns", r#"<p>Dropdown components that open on click, providing a list of selectable options.</p><div class="showcase-grid"><label class="ui-select-label">Select Device to Update<select class="ui-select" data-ui-select><option>Select a device</option><option>sdb - 🔒 Unlocked</option><option>sdc - 🔒 Unlocked</option><option>sdd - 🔒 Locked</option></select></label><label class="ui-select-label">Strategy<select class="ui-select" data-ui-select><option>Select a strategy</option><option>Safe Key Rotation</option><option>Replace Primary Key</option><option>Add to Slot 2</option></select></label><label class="ui-select-label">Required Selection<select class="ui-select" required><option>Please select an option</option><option>Option 1</option></select></label><label class="ui-select-label ui-select--error">Select with Error<select class="ui-select"><option>Select an option</option></select><span class="ui-input__error">This field is required</span></label><label class="ui-select-label">Disabled Selection<select class="ui-select" disabled><option>Selected Option</option></select></label></div><div class="showcase-item"><h4>Usage Notes</h4><ul><li>Click anywhere on the dropdown trigger to open the options list</li><li>Keyboard accessible</li></ul></div>"#, false));
    panels.push(section("slider", "Slider Component", r#"<p>Range slider component for selecting numeric values within a min/max range.</p><div class="showcase-grid"><div class="showcase-item"><h4>Basic Slider</h4><input class="ui-slider" type="range" min="0" max="100" value="50" data-ui-slider><p>Value: <span data-slider-value>50</span></p></div><div class="showcase-item"><h4>Slider with Labels</h4><div class="slider-labels"><span>More Leases</span><span>More Reservations</span></div><input class="ui-slider" type="range" value="25" data-ui-slider></div><div class="showcase-item"><h4>Slider with Step</h4><input class="ui-slider" type="range" step="5" value="75" data-ui-slider></div><div class="showcase-item"><h4>Disabled Slider</h4><input class="ui-slider" type="range" value="75" disabled></div><div class="showcase-item"><h4>DHCP Reservation Example</h4><input class="ui-slider" type="range" min="8" max="247" value="50" data-ui-slider><div>Reserved Range: <code>192.168.123.2 - 192.168.123.51</code></div><div>Pool Range: <code>192.168.123.52 - 192.168.123.250</code></div></div></div>"#, false));
    panels.push(section("textbox", "TextBox Component", r#"<p>Reliable text display component for logs, code, terminal output, and other text content.</p><div class="showcase-grid"><div class="showcase-item"><h4>Log Variant</h4><div class="text-box text-box--log"><header>System Logs <button class="ui-button ui-button--small" data-copy-textbox>Copy</button><button class="ui-button ui-button--secondary ui-button--small" data-refresh-log>Refresh</button></header><pre data-log-content>[2025-12-08 18:53:57] [INFO] Starting reinstallation of legacy installer tab: testTab
[2025-12-08 18:55:28] [INFO] Legacy installer tab 'testTab' reinstalled successfully</pre></div></div><div class="showcase-item"><h4>Code Variant</h4><pre class="text-box text-box--code">function calculateTotal(items) { return items.reduce((sum, item) =&gt; sum + (item.price * item.quantity), 0); }</pre></div><div class="showcase-item"><h4>Terminal Variant</h4><pre class="text-box text-box--terminal">$ npm install -g serve
$ serve -s build</pre></div><div class="showcase-item"><h4>With Placeholder</h4><div class="text-box text-box--log"><em>No log entries yet. Logs will appear here when available.</em></div></div></div>"#, false));
    panels.push(section("upload-components", "Upload Components", r#"<p>New components for the upload tablet: Breadcrumbs, IconButton, and FileInput</p><div class="showcase-grid"><div class="showcase-item"><h4>Breadcrumbs</h4><nav class="breadcrumbs" data-ui-breadcrumbs><button>nas</button><span>/</span><button>media</button><span>/</span><strong>kids</strong></nav><p>Current path: <code data-breadcrumb-path>/mnt/nas/media/kids</code></p><button class="ui-button ui-button--secondary ui-button--small" data-reset-breadcrumbs>Reset to Root</button></div><div class="showcase-item"><h4>IconButton</h4><button class="icon-button" aria-label="Refresh">⟳</button><button class="icon-button icon-button--circle" aria-label="Sync">↻</button><button class="icon-button" disabled aria-label="Disabled">⚙</button></div><div class="showcase-item"><h4>FileInput</h4><label class="file-input"><input type="file" data-ui-file-input><span data-file-input-label>Choose file</span></label></div></div>"#, false));
    panels.push(section("progress-bar", "Progress Bar", r#"<div class="showcase-grid"><div class="showcase-item"><h4>Basic Progress</h4><div class="progress-bar"><div class="progress" style="width:25%"></div></div><div class="progress-bar"><div class="progress" style="width:50%"></div></div><div class="progress-bar"><div class="progress" style="width:75%"></div></div></div><div class="showcase-item"><h4>Upload Progress</h4><div class="upload-progress uploading"><div class="upload-header"><span>📤</span><span class="filename">sample.iso</span></div><div class="progress-section"><div class="progress-bar-container"><div class="progress-bar" style="width:64%"><span class="progress-text">64%</span></div></div></div></div></div></div>"#, false));
    panels.push(section("table", "Table", r#"<div class="showcase-item"><h4>Service Table</h4><div class="ui-table-container"><table class="ui-table"><thead><tr><th>Name</th><th>Status</th><th>Version</th><th>Action</th></tr></thead><tbody><tr><td>Data Generator</td><td><span class="ui-badge ui-badge--success">active</span></td><td>1.0.0</td><td><button class="ui-button ui-button--small">Inspect</button></td></tr><tr><td>Health Monitor</td><td><span class="ui-badge ui-badge--success">active</span></td><td>1.0.0</td><td><button class="ui-button ui-button--small">Run</button></td></tr></tbody></table></div></div>"#, false));
    panels.push(section("collapsible", "Collapsible", r#"<div class="showcase-grid"><details class="collapsible"><summary>Open details</summary><p>Composable details content.</p></details><details class="collapsible" open><summary>Open by default</summary><pre>receipt: test.component.collapsible.v1</pre></details><details class="collapsible" data-ui-collapsible><summary>Interactive collapsible</summary><p>Click summary to open or close.</p></details></div>"#, false));
    panels.push(section("modals", "Modals", r#"<div class="showcase-row"><button class="ui-button ui-button--small" data-ux-modal-open="small">Open small modal</button><button class="ui-button" data-ux-modal-open="medium">Open medium modal</button><button class="ui-button ui-button--large" data-ux-modal-open="fullscreen">Open fullscreen modal</button></div><div class="showcase-grid"><article class="ui-card" data-modal-size="small"><h4>Small modal</h4><p>Compact confirm or short choice.</p></article><article class="ui-card" data-modal-size="medium"><h4>Medium modal</h4><p>Regular settings or detail dialog.</p></article><article class="ui-card" data-modal-size="fullscreen"><h4>Fullscreen modal</h4><p>Focused full-screen workflow.</p></article></div><div class="ui-modal-backdrop" data-ux-modal-demo-backdrop aria-hidden="true"><section class="ui-modal medium" role="dialog" aria-modal="true" data-ux-modal-demo-window><h4 data-ux-modal-demo-title>Medium modal</h4><p data-ux-modal-demo-body>Regular dialog body.</p><div class="ui-modal-actions"><button class="ui-button ui-button--secondary" data-ux-modal-close>Cancel</button><button class="ui-button" data-ux-modal-close>Confirm</button></div></section></div>"#, false));
    format!(r#"<section class="test-panel active" data-tab-panel="showcase"><div class="component-showcase" data-tab-scope="showcase" data-component-showcase="og-test"><div class="ui-tab-group" role="tablist" aria-label="Component showcase categories">{tabs}</div><div class="showcase-content">{panels}</div></div></section>"#, tabs = render_category_chip_grid(), panels = panels.join(""))
}

fn render_test_services() -> String {
    r#"<section class="test-panel" data-tab-panel="services"><div class="services-grid"><article class="test-card active"><div class="test-card-header"><div class="test-card-title"><h3>Data Generator</h3><span class="status-badge active">active</span></div><button class="expand-button" data-test-card-expand>+</button></div><div class="test-card-content"><p class="test-card-description">Generate sample datasets for testing and development</p><div class="test-card-meta"><span class="version">v1.0.0</span><span class="last-updated">Updated: honest static quarry sample</span></div><div class="test-card-expanded" hidden><div class="test-actions"><button class="primary-action" data-testtab-not-wired="true" aria-disabled="true">Perform Action</button><button class="secondary-action" data-testtab-not-wired="true" aria-disabled="true">Generate Data</button></div><div class="capabilities"><h4>Capabilities:</h4><ul><li>Random Data</li><li>User Data</li><li>Product Data</li><li>Transaction Data</li></ul></div></div></div></article><article class="test-card active"><div class="test-card-title"><h3>Analytics Processor</h3><span class="status-badge active">active</span></div><p>Process and analyze datasets using pandas and numpy</p><span class="capability enabled">Statistical Analysis</span><span class="capability enabled">Data Correlation</span></article><article class="test-card active"><div class="test-card-title"><h3>External API Client</h3><span class="status-badge active">active</span></div><p>Fetch data from external APIs with timeout and error handling</p><span class="capability enabled">HTTP Requests</span><span class="capability enabled">JSON Parsing</span></article><article class="test-card active"><div class="test-card-title"><h3>Health Monitor</h3><span class="status-badge active">active</span></div><p>Monitor the health and status of legacy installer tab dependencies</p><button class="ui-button ui-button--primary" data-test-health-check>Run Health Check</button></article></div></section>"#.to_string()
}

fn render_test_config() -> String {
    r#"<section class="test-panel" data-tab-panel="config"><div class="config-panel"><h3>Configuration</h3><div class="config-details"><div class="config-section"><h4>Basic Information</h4><p><strong>Name:</strong> Test</p><p><strong>Description:</strong> Component showcase and legacy installer tab test surface</p><p><strong>Version:</strong> 1.0.0</p></div><div class="config-section"><h4>Capabilities</h4><ul><li><span class="capability enabled">component showcase: Enabled</span></li><li><span class="capability enabled">chrome interactivity: Enabled</span></li><li><span class="capability disabled">legacy /api/test data actions: Not wired in Crown</span></li></ul></div><div class="config-section"><h4>Settings</h4><ul><li><strong>default tab:</strong> Component Showcase</li><li><strong>category switching:</strong> Crown chrome toggle</li><li><strong>source:</strong> quarry tablets/testTab + styles/common/ui</li></ul></div></div></div></section>"#.to_string()
}

fn render_test_health() -> String {
    r#"<section class="test-panel" data-tab-panel="health"><div class="health-panel"><div class="health-header"><h3>Health Status</h3><button class="ui-button ui-button--primary" data-test-health-check>Run Health Check</button></div><div class="health-details"><div class="health-status healthy"><h4>Overall Status: READY</h4><p>Last checked: browser button writes live chrome readback below.</p></div><div class="dependencies-status"><h4>Dependencies</h4><ul><li><span class="dependency healthy">rust_shell: ✓ Available</span></li><li><span class="dependency healthy">ux_library: ✓ Available</span></li><li><span class="dependency unhealthy">legacy /api/test backend: ✗ Not wired in Crown</span></li></ul></div><pre class="readout" data-test-health-output>{"schema":"coronatio.test.health.v1","status":"ready"}</pre></div></div></section>"#.to_string()
}

fn render_test_showcase() -> String {
    format!(
        r#"<section class="pane" id="pane-test" data-pane-panel="test" data-view-panel="test" role="tabpanel" aria-label="Test"><div class="test-tablet" data-tab-scope="test" data-native-stock-test="true" data-admin-viewport="test" data-react-quarry="legacy-tabs/testTab" data-ux-library="og-styles-common-ui" data-ux-registry="og-test-bedrock"><div class="ui-tab-group" role="tablist" aria-label="Test sections"><button type="button" class="ui-tab ui-tab--active active" data-tab-id="showcase" aria-selected="true" data-depth="2"><span class="ui-tab__content"><span class="ui-tab__label">Component Showcase</span></span></button><button type="button" class="ui-tab" data-tab-id="services" aria-selected="false" data-depth="2"><span class="ui-tab__content"><span class="ui-tab__label">Services</span></span></button><button type="button" class="ui-tab" data-tab-id="config" aria-selected="false" data-depth="2"><span class="ui-tab__content"><span class="ui-tab__label">Configuration</span></span></button><button type="button" class="ui-tab" data-tab-id="health" aria-selected="false" data-depth="2"><span class="ui-tab__content"><span class="ui-tab__label">Health Status</span></span></button></div><div class="test-tablet-content">{showcase}{services}{config}{health}</div></div></section>"#,
        showcase = render_component_showcase(),
        services = render_test_services(),
        config = render_test_config(),
        health = render_test_health()
    )
}
