fn shell_unbound_client() -> &'static str {
    r####"    const dnsState = { dns: {}, resolver: null, pickedMac: null };
    const dnsArray = value => Array.isArray(value) ? value : [];
    const dnsValue = (value, fallback = '—') => value === undefined || value === null || value === '' ? fallback : String(value);
    const dnsAddress = row => row?.address || row?.ip || row?.target || row?.value || row?.declared_reservation?.ip || row?.observed_lease?.ip || '—';
    const dnsNameRows = () => {
      const entries = [];
      dnsArray(dnsState.dns.records || dnsState.dns.names || dnsState.dns.data?.records).forEach(row => entries.push({ name: row.name || row.hostname || row.alias, address: dnsAddress(row), mac: row.mac || row.device_mac }));
      dnsArray(dnsState.dns.aliases || dnsState.dns.cnames).forEach(row => entries.push({ name: row.name || row.alias, address: dnsAddress(row) }));
      dnsArray(identityState?.roster).forEach(device => dnsArray(device.dns_names).forEach(name => entries.push({ name, address: dnsAddress(device), mac: device.mac })));
      return [...new Map(entries.filter(row => row.name).map(row => [String(row.name).toLowerCase(), row])).values()].sort((a, b) => String(a.name).localeCompare(String(b.name)));
    };
    async function dnsJson(route, options = {}) { return identityJson(route, options); }
    function dnsSetState(message) { document.querySelectorAll('[data-dns-state]').forEach(node => { node.textContent = message; }); }
    function renderDnsNames() { const target = document.querySelector('[data-dns-names]'); if (!target) return; const rows = dnsNameRows(); target.innerHTML = rows.length ? `<table class="ui-table dns-name-table"><thead><tr><th>Name</th><th>Address</th></tr></thead><tbody>${rows.map(row => `<tr><td><code>${escapeHtml(dnsValue(row.name))}</code></td><td><code>${escapeHtml(dnsValue(row.address))}</code></td></tr>`).join('')}</tbody></table>` : '<p class="dns-empty">No LAN names are registered.</p>'; }
    function renderDnsModalRoster() { const target = document.querySelector('[data-dns-device-roster]'); if (!target) return; const devices = dnsArray(identityState?.roster); target.innerHTML = `<table class="identity-roster"><thead><tr><th>Device</th><th>Address</th><th>Names</th><th>Pick</th></tr></thead><tbody>${devices.map(device => `<tr data-device-mac="${escapeHtml(dnsValue(device.mac, ''))}"><td><code>${escapeHtml(dnsValue(device.mac))}</code></td><td><code>${escapeHtml(dnsAddress(device))}</code></td><td>${escapeHtml(dnsArray(device.dns_names).join(', ') || '—')}</td><td><button type="button" class="ui-button ui-button--secondary ui-button--small" data-dns-device-pick="${escapeHtml(dnsValue(device.mac, ''))}">Pick</button></td></tr>`).join('') || '<tr><td colspan="4">No devices reported.</td></tr>'}</tbody></table>`; }
    function renderDnsModalRecords() { const target = document.querySelector('[data-dns-modal-records]'); if (!target) return; const rows = dnsNameRows(); target.innerHTML = `<h3>Records</h3><table class="ui-table"><thead><tr><th>Name</th><th>Address</th></tr></thead><tbody>${rows.map(row => `<tr><td>${escapeHtml(dnsValue(row.name))}</td><td>${escapeHtml(dnsValue(row.address))}</td></tr>`).join('') || '<tr><td colspan="2">No records reported.</td></tr>'}</tbody></table>`; }
    function resolverReceipt(envelope) { for (const receipt of [envelope?.receipt, envelope?.data?.receipt, envelope?.result?.receipt, envelope?.data, envelope?.result, envelope]) if (receipt && typeof receipt === 'object' && !Array.isArray(receipt)) return receipt; return {}; }
    function resolverPreset(upstreams) { const presets = { quad9: ['9.9.9.9', '149.112.112.112'], cloudflare: ['1.1.1.1', '1.0.0.1'], google: ['8.8.8.8', '8.8.4.4'] }; return Object.entries(presets).find(([, addresses]) => addresses.length === upstreams.length && addresses.every((address, index) => address === upstreams[index]))?.[0] || 'custom'; }
    function renderResolverStatus(status) { const target = document.querySelector('[data-dns-resolver-status]'); if (!target) return; const receipt = resolverReceipt(status); const upstreams = dnsArray(receipt.upstreams).map(String); const updated = receipt.blocklistLastUpdate === null ? null : new Date(receipt.blocklistLastUpdate * 1000).toLocaleString(); const adblockInput = document.querySelector('[data-dns-adblock]'); const upstreamInput = document.querySelector('[data-dns-upstream]'); const dotInput = document.querySelector('[data-dns-dot]'); if (adblockInput && typeof receipt.adblockEnabled === 'boolean') adblockInput.checked = receipt.adblockEnabled; if (upstreamInput) upstreamInput.value = resolverPreset(upstreams); if (dotInput && typeof receipt.dnsOverTls === 'boolean') dotInput.checked = receipt.dnsOverTls; target.innerHTML = [['Upstreams', upstreams.join(', ')], ['Blocklist', receipt.blocklistDomainCount], ['Last update', updated], ['Unbound service', receipt.unboundActive ? 'Active' : 'Inactive']].map(([label, value]) => `<div class="dns-info-row"><span>${escapeHtml(label)}</span><strong>${escapeHtml(dnsValue(value))}</strong></div>`).join(''); }
    async function hydrateDns() { if (!viewportFamilyAdmitted('unbound')) return; dnsSetState('Reading local names…'); try { const [roster, dns, resolver] = await Promise.all([dnsJson('/api/network/device'), dnsJson('/api/v1/network/dns/read'), dnsJson('/api/v1/network/dns/resolver/status').catch(error => error?.message?.includes('404') ? null : Promise.reject(error))]); identityState.roster = identityRows(roster); identityState.dns = dns; dnsState.dns = dns; dnsState.resolver = resolver; renderDnsNames(); renderDnsModalRoster(); renderDnsModalRecords(); if (resolver) renderResolverStatus(resolver); else document.querySelector('[data-dns-resolver-status]')?.replaceChildren(Object.assign(document.createElement('p'), { textContent: 'Resolver controls are pending the parallel Caduceus lane.' })); dnsSetState('Local names are current.'); } catch (failure) { dnsSetState(`Local DNS unavailable: ${failure.message}`); } }
    function openDnsModal() { const modal = document.querySelector('[data-dns-add-modal]'); if (!modal) return; modal.hidden = false; renderDnsModalRoster(); renderDnsModalRecords(); document.querySelector('[data-dns-new-name]')?.focus(); }
    function closeDnsModal() { const modal = document.querySelector('[data-dns-add-modal]'); if (modal) modal.hidden = true; dnsState.pickedMac = null; const picked = document.querySelector('[data-dns-picked-device]'); if (picked) picked.textContent = 'Choose a device for this name.'; }
    async function saveDnsName() { const name = document.querySelector('[data-dns-new-name]')?.value.trim(); const result = document.querySelector('[data-dns-add-result]'); if (!name || !dnsState.pickedMac) { if (result) result.textContent = 'Enter a name and pick a device.'; return; } if (result) result.textContent = 'Adding name…'; try { await dnsJson('/api/v1/network/dns/device-name/create', { method: 'POST', body: JSON.stringify({ name, mac: dnsState.pickedMac }) }); showCoronatioToast('LAN name added.', 'success'); closeDnsModal(); await hydrateDns(); } catch (failure) { if (result) result.textContent = `Unable to add name: ${failure.message}`; showCoronatioToast(failure?.message || 'DNS request failed', 'error'); } }
    async function updateDnsBlocklist() { try { const receipt = await dnsJson('/api/v1/network/dns/blocklist/update', { method: 'POST', body: JSON.stringify({}) }); const state = receipt?.state || receipt?.data?.state || receipt?.receipt?.state || 'accepted'; showCoronatioToast(`Blocklist update: ${state}.`, 'success'); await hydrateDns(); } catch (failure) { showCoronatioToast(failure?.message || 'Blocklist update pending the parallel lane.', 'error'); } }
    async function setDnsAdblock(enabled) { try { await dnsJson('/api/v1/network/dns/adblock', { method: 'POST', body: JSON.stringify({ enabled }) }); showCoronatioToast(`Ad blocking ${enabled ? 'enabled' : 'disabled'}.`, 'success'); await hydrateDns(); } catch (failure) { showCoronatioToast(failure?.message || 'Ad blocking change pending the parallel lane.', 'error'); await hydrateDns(); } }
    async function saveDnsUpstream() { const preset = document.querySelector('[data-dns-upstream]')?.value; const dot = Boolean(document.querySelector('[data-dns-dot]')?.checked); const existing = dnsArray(resolverReceipt(dnsState.resolver).upstreams).join(', '); const custom = preset === 'custom' ? window.prompt('Enter one or more resolver IP addresses, separated by commas.', existing)?.split(',').map(address => address.trim()).filter(Boolean) : null; if (preset === 'custom' && !custom?.length) return; const payload = preset === 'custom' ? { preset: null, custom, dot } : { preset, custom: null, dot }; try { await dnsJson('/api/v1/network/dns/upstream', { method: 'POST', body: JSON.stringify(payload) }); showCoronatioToast('Resolver settings saved.', 'success'); await hydrateDns(); } catch (failure) { showCoronatioToast(failure?.message || 'Resolver change pending the parallel lane.', 'error'); } }
    document.addEventListener('click', async event => { if (event.target.closest?.('[data-dns-add-name]')) return openDnsModal(); if (event.target.closest?.('[data-dns-add-close]')) return closeDnsModal(); if (event.target.closest?.('[data-dns-add-save]')) return saveDnsName(); const pick = event.target.closest?.('[data-dns-device-pick]'); if (pick) { dnsState.pickedMac = pick.dataset.dnsDevicePick; const selected = document.querySelector('[data-dns-picked-device]'); if (selected) selected.textContent = `Selected device: ${dnsState.pickedMac}`; return; } if (event.target.closest?.('[data-dns-blocklist-update]')) return updateDnsBlocklist(); if (event.target.closest?.('[data-dns-upstream-save]')) return saveDnsUpstream(); if (event.target.closest?.('[data-dns-refresh]')) return hydrateDns(); }, true);
    document.addEventListener('change', event => { const adblock = event.target.closest?.('[data-dns-adblock]'); if (adblock) void setDnsAdblock(adblock.checked); }, true);
"####
}
