fn shell_wake_on_lan_client() -> &'static str {
    r####"    const wakeOnLanState = { devices: [] };
    function wakeOnLanRows(payload) { for (const source of [payload, payload?.leases, payload?.reservations, payload?.data?.leases, payload?.result?.leases, payload?.items]) if (Array.isArray(source)) return source; return []; }
    function wakeOnLanDevice(row) { const mac = String(row?.mac || row?.macAddress || row?.['hw-address'] || row?.hwAddress || '').toUpperCase(); const ip = String(row?.ip || row?.ipAddress || row?.['ip-address'] || row?.address || '').trim(); const name = String(row?.hostname || row?.hostName || row?.name || ip || 'Unknown device').trim(); return mac && ip ? { mac, ip, name } : null; }
    function wakeOnLanMessage(payload) { return payload?.error || payload?.message || payload?.firstMissingSignal || 'Wake-on-LAN is unavailable'; }
    async function wakeOnLanJson(route, options = {}) { const response = await fetch(route, { cache: 'no-store', headers: options.body ? { 'content-type': 'application/json' } : {}, ...options }); const body = await response.json().catch(() => ({})); if (!response.ok || body?.ok === false) throw body; return body; }
    function renderWakeOnLan() { const rows = document.querySelector('[data-wake-on-lan-rows]'); if (!rows) return; rows.innerHTML = wakeOnLanState.devices.map(device => { return `<li class="wake-on-lan-device"><div class="wake-on-lan-device__identity"><strong>${escapeHtml(device.name)}</strong><code>${escapeHtml(device.mac)}</code><span>${escapeHtml(device.ip)}</span></div><div class="wake-on-lan-device__action"><button type="button" class="ui-button ui-button--primary ui-button--small" data-wake-on-lan-wake="${escapeHtml(device.ip)}">Wake</button></div></li>`; }).join('') || '<li class="wake-on-lan-empty">No DHCP devices are available.</li>'; }
    async function hydrateWakeOnLan() { if (!viewportFamilyAdmitted('wake-on-lan')) return; const error = document.querySelector('[data-wake-on-lan-error]'); if (error) error.hidden = true; try { const { leases, reservations } = await wakeOnLanJson('/api/wakeonlan/devices'); const devices = new Map(); [...wakeOnLanRows(leases), ...wakeOnLanRows(reservations)].map(wakeOnLanDevice).filter(Boolean).forEach(device => devices.set(device.mac, device)); wakeOnLanState.devices = [...devices.values()]; renderWakeOnLan(); } catch (failure) { if (error) { error.hidden = false; error.textContent = wakeOnLanMessage(failure); } } }
    document.addEventListener('click', async event => { const button = event.target.closest?.('[data-wake-on-lan-wake]'); if (!button) return; const device = wakeOnLanState.devices.find(candidate => candidate.ip === button.dataset.wakeOnLanWake); if (!device) return; try { await wakeOnLanJson('/api/wakeonlan/wake', { method: 'POST', body: JSON.stringify({ mac: device.mac, ip: device.ip }) }); showCoronatioToast('Packet sent — waiting…', 'success'); } catch (failure) { showCoronatioToast(wakeOnLanMessage(failure), 'error'); } });
"####
}
