const BACKBLAZE_STATE_PATH: &str = "/var/lib/coronatio/backblaze_state.json";
const BACKBLAZE_KEYMAN_EXPORT: &str = "/vault/keyman/exportkey.sh";

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
struct BackblazeState { #[serde(default)] buckets: BTreeMap<String, BackblazeBucketState> }
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
struct BackblazeBucketState { running: bool, last_run_at: Option<u64>, last_run_ok: Option<bool> }

fn backblaze_state_path() -> PathBuf { env::var("CORONATIO_BACKBLAZE_STATE").map(PathBuf::from).unwrap_or_else(|_| PathBuf::from(BACKBLAZE_STATE_PATH)) }
fn backblaze_state() -> BackblazeState { std::fs::read_to_string(backblaze_state_path()).ok().and_then(|s| serde_json::from_str(&s).ok()).unwrap_or_default() }
fn write_backblaze_state(state: &BackblazeState) { if let Ok(raw)=serde_json::to_vec(state) { let path=backblaze_state_path(); if let Some(parent)=path.parent() { let _=std::fs::create_dir_all(parent); let tmp=parent.join(format!(".backblaze.{}.tmp",std::process::id())); if std::fs::write(&tmp,raw).is_ok() { let _=std::fs::rename(tmp,path); } } } }

fn backblaze_config_value() -> Result<serde_json::Value,String> { let (_, root)=load_homeserver_json_sync()?; let config=root.get("tabs").and_then(|v|v.get("backblaze")).and_then(|v|v.get("config")).cloned().unwrap_or_else(||serde_json::json!({})); if config.get("buckets").and_then(|v|v.as_array()).is_some() { return Ok(config); } let bucket=config.get("bucket").and_then(|v|v.as_str()).unwrap_or("").trim(); if bucket.is_empty() { return Ok(serde_json::json!({"buckets":[]})); } let prefix=config.get("prefix").and_then(|v|v.as_str()).unwrap_or(""); let items=config.get("paths").and_then(|v|v.as_array()).cloned().unwrap_or_default().into_iter().filter_map(|v|v.as_str().map(|path|serde_json::json!({"path":path}))).collect::<Vec<_>>(); Ok(serde_json::json!({"buckets":[{"bucket":bucket,"prefix":prefix,"encrypted":true,"items":items}]})) }
fn normalized_config(raw: serde_json::Value) -> Result<serde_json::Value,String> { let buckets=raw.get("buckets").and_then(|v|v.as_array()).ok_or("buckets must be an array")?; let mut out=Vec::new(); for b in buckets { let bucket=b.get("bucket").and_then(|v|v.as_str()).unwrap_or("").trim(); if bucket.is_empty() || bucket.contains('/') { return Err("bucket is invalid".into()); } let prefix=b.get("prefix").and_then(|v|v.as_str()).unwrap_or("").trim().trim_matches('/'); let encrypted=b.get("encrypted").and_then(|v|v.as_bool()).unwrap_or(true); let items=b.get("items").and_then(|v|v.as_array()).cloned().unwrap_or_default().into_iter().filter_map(|i| { let p=i.get("path").and_then(|v|v.as_str()).unwrap_or("").trim(); (!p.is_empty() && p.starts_with('/')).then(||serde_json::json!({"path":p})) }).collect::<Vec<_>>(); out.push(serde_json::json!({"bucket":bucket,"prefix":prefix,"encrypted":encrypted,"items":items})); } Ok(serde_json::json!({"buckets":out})) }
fn save_backblaze_config(config: serde_json::Value) -> Result<(),String> { let path=homeserver_json_path(); let raw=std::fs::read_to_string(&path).map_err(|_|"homeserver.json unreadable")?; let mut root:serde_json::Value=serde_json::from_str(&raw).map_err(|_|"homeserver.json invalid")?; root["tabs"]["backblaze"]["config"]=config; std::fs::write(path,serde_json::to_vec_pretty(&root).map_err(|_|"config encode failed")?).map_err(|_|"config write failed".to_string()).map(|_|()) }
fn backblaze_bucket(config:&serde_json::Value,name:&str)->Option<serde_json::Value>{config.get("buckets")?.as_array()?.iter().find(|b|b.get("bucket").and_then(|v|v.as_str())==Some(name)).cloned()}
fn keyman_service(bucket:&str)->String { let mut s=String::from("backblaze_"); for c in bucket.chars(){ if c.is_ascii_alphanumeric(){s.push(c.to_ascii_lowercase())}else{s.push('_')} } s }
fn authorize_bucket(bucket:&str)->Result<(),String>{ let service=keyman_service(bucket); let export=Command::new(BACKBLAZE_KEYMAN_EXPORT).arg(&service).output().map_err(|_|"Keyman newkey service unavailable")?; if !export.status.success(){return Err("Keyman newkey service unavailable".into())} let account=env::var("B2_ACCOUNT_ID").map_err(|_|"B2 credentials unavailable")?; let key=env::var("B2_APPLICATION_KEY").or_else(|_|env::var("B2_ACCOUNT_KEY")).map_err(|_|"B2 credentials unavailable")?; let auth=base64::Engine::encode(&base64::engine::general_purpose::STANDARD,format!("{}:{}",account,key)); let out=Command::new("curl").args(["-fsS","-u",&auth,"https://api.backblazeb2.com/b2api/v2/b2_authorize_account"]).output().map_err(|_|"B2 authorize failed")?; if !out.status.success(){return Err("B2 authorize failed".into())} let value:serde_json::Value=serde_json::from_slice(&out.stdout).map_err(|_|"B2 authorize returned invalid response")?; let api=value.get("apiUrl").and_then(|v|v.as_str()).ok_or("B2 authorize returned no API URL")?; let token=value.get("authorizationToken").and_then(|v|v.as_str()).ok_or("B2 authorize returned no token")?; let listed=Command::new("curl").args(["-fsS","-H",&format!("Authorization: {}",token),&format!("{}/b2api/v2/b2_list_buckets?accountId={}&bucketName={}&namePrefix=",api,account,bucket)]).output().map_err(|_|"B2 bucket verification failed")?; if !listed.status.success(){return Err("B2 bucket reachability verification failed".into())} let found:serde_json::Value=serde_json::from_slice(&listed.stdout).map_err(|_|"B2 bucket verification returned invalid response")?; if found.get("buckets").and_then(|v|v.as_array()).map(|a|a.iter().any(|b|b.get("bucketName").and_then(|v|v.as_str())==Some(bucket))).unwrap_or(false){Ok(())}else{Err("B2 bucket is not reachable".into())} }
fn backblaze_public(config:serde_json::Value)->serde_json::Value { let mut state=backblaze_state(); let buckets=config.get("buckets").and_then(|v|v.as_array()).cloned().unwrap_or_default().into_iter().map(|mut b| { let name=b.get("bucket").and_then(|v|v.as_str()).unwrap_or(""); let s=state.buckets.remove(name).unwrap_or_default(); b["status"]=serde_json::json!({"running":s.running,"last_run_at":s.last_run_at,"last_run_ok":s.last_run_ok}); b }).collect::<Vec<_>>(); serde_json::json!({"buckets":buckets}) }
async fn backblaze_buckets_get_route()->Response{match backblaze_config_value(){Ok(c)=>(StatusCode::OK,Json(backblaze_public(c))).into_response(),Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(serde_json::json!({"ok":false,"reason":e}))).into_response()}}
async fn backblaze_bucket_post_route(headers: axum::http::HeaderMap, Json(body):Json<serde_json::Value>)->Response{let readback=mutation_staff_intent(&mutation_authority(),&headers,"POST","/api/backblaze/buckets","backblaze bucket",body.clone());if !readback.ok{return (mutation_response_status(&readback),Json(serde_json::json!({"ok":false,"reason":readback.first_missing_signal}))).into_response()} let name=body.clone().get("bucket").and_then(|v|v.as_str()).unwrap_or("").trim().to_string(); if let Err(e)=authorize_bucket(&name){return(StatusCode::BAD_REQUEST,Json(serde_json::json!({"ok":false,"reason":e}))).into_response()} let mut c=match backblaze_config_value(){Ok(v)=>v,Err(e)=>return(StatusCode::BAD_REQUEST,Json(serde_json::json!({"ok":false,"reason":e}))).into_response()}; let mut b=body; b["bucket"]=serde_json::json!(&name); if b.get("encrypted").is_none(){b["encrypted"]=serde_json::json!(true)}; if b.get("items").is_none(){b["items"]=serde_json::json!([])}; let mut arr=c["buckets"].as_array().cloned().unwrap_or_default(); arr.retain(|x|x.get("bucket").and_then(|v|v.as_str())!=Some(name.as_str())); arr.push(b); c=normalized_config(serde_json::json!({"buckets":arr})).unwrap_or(c); match save_backblaze_config(c){Ok(_)=>(StatusCode::OK,Json(serde_json::json!({"ok":true}))).into_response(),Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(serde_json::json!({"ok":false,"reason":e}))).into_response()}}
async fn backblaze_bucket_delete_route(headers:axum::http::HeaderMap,Path(bucket):Path<String>)->Response{let r=mutation_staff_intent(&mutation_authority(),&headers,"DELETE","/api/backblaze/buckets/:bucket","backblaze bucket",serde_json::json!({"bucket":bucket}));if !r.ok{return(mutation_response_status(&r),Json(serde_json::json!({"ok":false,"reason":r.first_missing_signal}))).into_response()} let c=match backblaze_config_value(){Ok(v)=>v,Err(e)=>return(StatusCode::BAD_REQUEST,Json(serde_json::json!({"ok":false,"reason":e}))).into_response()};let arr=c["buckets"].as_array().unwrap_or(&vec![]).iter().filter(|b|b.get("bucket").and_then(|v|v.as_str())!=Some(bucket.as_str())).cloned().collect::<Vec<_>>();match save_backblaze_config(serde_json::json!({"buckets":arr})){Ok(_)=>(StatusCode::OK,Json(serde_json::json!({"ok":true}))).into_response(),Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(serde_json::json!({"ok":false,"reason":e}))).into_response()}}
async fn backblaze_items_get_route(Path(bucket):Path<String>)->Response{match backblaze_config_value().ok().and_then(|c|backblaze_bucket(&c,&bucket)){Some(b)=>(StatusCode::OK,Json(b)).into_response(),None=>(StatusCode::NOT_FOUND,Json(serde_json::json!({"ok":false,"reason":"bucket not configured"}))).into_response()}}
async fn backblaze_item_post_route(headers:axum::http::HeaderMap,Path(bucket):Path<String>,Json(item):Json<serde_json::Value>)->Response{backblaze_item_mutate(headers,bucket,item,false).await}
async fn backblaze_item_delete_route(headers:axum::http::HeaderMap,Path(bucket):Path<String>,Json(item):Json<serde_json::Value>)->Response{backblaze_item_mutate(headers,bucket,item,true).await}
async fn backblaze_item_mutate(headers:axum::http::HeaderMap,bucket:String,item:serde_json::Value,remove:bool)->Response{let r=mutation_staff_intent(&mutation_authority(),&headers,"POST","/api/backblaze/buckets/:bucket/items","backblaze item",item.clone());if !r.ok{return(mutation_response_status(&r),Json(serde_json::json!({"ok":false,"reason":r.first_missing_signal}))).into_response()}let mut c=match backblaze_config_value(){Ok(v)=>v,Err(e)=>return(StatusCode::BAD_REQUEST,Json(serde_json::json!({"ok":false,"reason":e}))).into_response()};let Some(mut b)=backblaze_bucket(&c,&bucket)else{return(StatusCode::NOT_FOUND,Json(serde_json::json!({"ok":false}))).into_response()};let p=item.get("path").and_then(|v|v.as_str()).unwrap_or("");let mut items=b["items"].as_array().cloned().unwrap_or_default();items.retain(|i|i.get("path").and_then(|v|v.as_str())!=Some(p));if !remove{items.push(serde_json::json!({"path":p}))}b["items"]=serde_json::json!(items);let arr=c["buckets"].as_array().unwrap_or(&vec![]).iter().map(|x|if x.get("bucket").and_then(|v|v.as_str())==Some(bucket.as_str()){b.clone()}else{x.clone()}).collect::<Vec<_>>();match save_backblaze_config(serde_json::json!({"buckets":arr})){Ok(_)=>(StatusCode::OK,Json(serde_json::json!({"ok":true}))).into_response(),Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(serde_json::json!({"ok":false,"reason":e}))).into_response()}}
async fn backblaze_toggle_route(headers:axum::http::HeaderMap,Path(bucket):Path<String>,Json(body):Json<serde_json::Value>)->Response{let mut c=match backblaze_config_value(){Ok(v)=>v,Err(e)=>return(StatusCode::BAD_REQUEST,Json(serde_json::json!({"ok":false,"reason":e}))).into_response()};let r=mutation_staff_intent(&mutation_authority(),&headers,"POST","/api/backblaze/buckets/:bucket/toggle","backblaze encryption",body.clone());if !r.ok{return(mutation_response_status(&r),Json(serde_json::json!({"ok":false}))).into_response()}let arr=c["buckets"].as_array().cloned().unwrap_or_default().into_iter().map(|mut x|{if x.get("bucket").and_then(|v|v.as_str())==Some(bucket.as_str()){x["encrypted"]=serde_json::json!(body.get("encrypted").and_then(|v|v.as_bool()).unwrap_or(true))}x}).collect::<Vec<_>>();match save_backblaze_config(serde_json::json!({"buckets":arr})){Ok(_)=>(StatusCode::OK,Json(serde_json::json!({"ok":true}))).into_response(),Err(e)=>(StatusCode::INTERNAL_SERVER_ERROR,Json(serde_json::json!({"ok":false}))).into_response()}}
fn execute_backblaze_bucket(bucket:String) {
    let config=backblaze_config_value().ok().and_then(|c|backblaze_bucket(&c,&bucket));
    let Some(config)=config else{return};
    let encrypted=config.get("encrypted").and_then(|v|v.as_bool()).unwrap_or(true);
    let items=config.get("items").and_then(|v|v.as_array()).cloned().unwrap_or_default();
    let paths=items.iter().filter_map(|i|i.get("path").and_then(|v|v.as_str())).collect::<Vec<_>>();
    let ok=if encrypted {
        let repo=format!("b2:{}:{}",bucket,config.get("prefix").and_then(|v|v.as_str()).unwrap_or(""));
        Command::new("restic").args(["--repo",&repo,"backup","--json"]).args(&paths).env("B2_ACCOUNT_ID",env::var("B2_ACCOUNT_ID").unwrap_or_default()).env("B2_ACCOUNT_KEY",env::var("B2_ACCOUNT_KEY").unwrap_or_default()).status().is_ok_and(|s|s.success())
    } else {
        // Plain mode intentionally uses the native B2 HTTP API and no new crate.
        paths.iter().all(|path| Command::new("curl").args(["-fsS","-X","POST","https://api.backblazeb2.com/b2api/v2/b2_upload_file","--data-binary",path]).status().is_ok_and(|s|s.success()))
    };
    let mut state=backblaze_state(); if let Some(e)=state.buckets.get_mut(&bucket){e.running=false;e.last_run_ok=Some(ok);} write_backblaze_state(&state);
}

async fn backblaze_run_bucket_route(headers:axum::http::HeaderMap,Path(bucket):Path<String>)->Response{let r=mutation_staff_intent(&mutation_authority(),&headers,"POST","/api/backblaze/buckets/:bucket/run","backblaze backup",serde_json::json!({"bucket":bucket}));if !r.ok{return(mutation_response_status(&r),Json(serde_json::json!({"ok":false}))).into_response()}let mut s=backblaze_state();let e=s.buckets.entry(bucket.clone()).or_default();if e.running{return(StatusCode::CONFLICT,Json(serde_json::json!({"ok":false,"reason":"backup already running"}))).into_response()}e.running=true;e.last_run_at=Some(now_unix_seconds());write_backblaze_state(&s);std::thread::spawn(move || execute_backblaze_bucket(bucket));(StatusCode::ACCEPTED,Json(serde_json::json!({"ok":true,"status":"queued"}))).into_response()}
fn now_unix_seconds()->u64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()}
