pub(crate) fn openvpn_manifest() -> IndicatorManifest {
    IndicatorManifest { id: "openvpn", topic_id: "vpn.status", order: 30, title: "VPN & Transmission Configuration", icon_id: "lock", initial_state: "loading", admin_interactive: true, render_indicator: render_openvpn_indicator, render_modal: render_openvpn_modal, collector: Some(openvpn_collector) }
}

fn render_openvpn_indicator(ctx: IndicatorRenderContext) -> String { let _ = ctx.session; r##"<button type="button" class="indicator loading openvpn-indicator" data-indicator="openvpn" data-modal-kind="openvpn" data-modal-title="VPN & Transmission Configuration" aria-label="VPN & Transmission Configuration" title="VPN & Transmission Configuration"><svg class="indicator-icon" data-packed-icon="lock" viewBox="0 0 24 24" aria-hidden="true"><path d="M7 10V8a5 5 0 0 1 10 0v2h2v11H5V10h2zm2 0h6V8a3 3 0 0 0-6 0v2zm2 4v3h2v-3h-2z"/></svg></button>"##.to_string() }
fn render_openvpn_modal(ctx: IndicatorRenderContext) -> String {
    let _ = ctx.session;
    r##"<div class="vpn-status-modal" data-modal-kind-body="openvpn"><div class="status-section"><div class="service-statuses"><div class="status-item loading"><span>VPN Status:</span><span class="status-value" data-modal-status data-route-read="/api/status/vpn/pia">Loading VPN…</span></div><div class="status-item loading"><span>Transmission Status:</span><span class="status-value" data-modal-secondary-status>Loading Transmission…</span></div></div></div>${indicatorAdminSection(`<div class="transmission-admin-details"><section aria-label="Transmission Onness"><h3>Transmission Onness</h3><div>Provider: <span data-transmission-detail="provider">Loading…</span></div><div>Forward port: <span data-transmission-detail="forwardPort">Loading…</span></div><div>Peer port: <span data-transmission-detail="peerPort">Loading…</span></div><div>RPC port: <span data-transmission-detail="rpcPort">Loading…</span></div><div>Namespace: <span data-transmission-condition="namespace">Loading…</span></div><div>Tunnel: <span data-transmission-condition="tunnel">Loading…</span></div><div>Forward: <span data-transmission-condition="forward">Loading…</span></div><div>Daemon: <span data-transmission-condition="daemon">Loading…</span></div><div>Peer port condition: <span data-transmission-condition="peerPort">Loading…</span></div><div>First missing signal: <span data-transmission-detail="firstMissingSignal">Loading…</span></div></section><section class="service-controls"><h3>transmissionVPN.service</h3><div>Active: <span data-transmission-service-active>Loading…</span></div><div>Enabled at boot: <span data-transmission-service-enabled>Loading…</span></div><div class="button-row"><button data-modal-fetch="/api/service/control" data-method="POST" data-service-action="start">Start</button><button data-modal-fetch="/api/service/control" data-method="POST" data-service-action="stop">Stop</button><button data-modal-fetch="/api/service/control" data-method="POST" data-service-action="enable">Enable at boot</button><button data-modal-fetch="/api/service/control" data-method="POST" data-service-action="disable">Disable at boot</button></div></section><section class="credentials-section"><h3>Transmission keys</h3><div data-transmission-key-presence="pia">PIA key: Loading…</div><div data-transmission-key-presence="transmission">Transmission key: Loading…</div><div class="credential-group"><input data-transmission-username autocomplete="username" placeholder="PIA Username"><input data-transmission-password type="password" autocomplete="new-password" placeholder="PIA Password"><button data-modal-fetch="/api/transmission/keys/replace" data-method="POST">Replace PIA Key</button></div><button data-modal-fetch="/api/transmission/keys/rotate" data-method="POST">Rotate Transmission RPC Key</button></section></div>`)}<pre class="readout action-output" data-modal-output></pre></div>"##.to_string()
}
fn openvpn_collector(session: Session) -> Result<serde_json::Value, String> { collect_indicator_topic("vpn.status", session) }
